import type {Language,Text} from './content';

type Stage={id:string;group:'environment'|'cognition'|'social-action';label:Text;summary:Text;children:Text[]};
const stages:Stage[]=[
 {id:'environment',group:'environment',label:{en:'Information environment',ro:'Mediul informațional'},summary:{en:'What information exists and can potentially reach a person.',ro:'Ce informație există și poate ajunge potențial la o persoană.'},children:[{en:'Available information',ro:'Informație disponibilă'},{en:'Source provenance',ro:'Proveniența sursei'}]},
 {id:'selection',group:'environment',label:{en:'Exposure and selection',ro:'Expunere și selecție'},summary:{en:'Which information is selected, ranked, repeated or encountered.',ro:'Ce informație este selectată, ordonată, repetată sau întâlnită.'},children:[{en:'Editorial selection',ro:'Selecție editorială'},{en:'Repeated exposure',ro:'Expunere repetată'},{en:'Recommendation / ranking context',ro:'Context de recomandare / ranking'}]},
 {id:'attention',group:'cognition',label:{en:'Attention and access',ro:'Atenție și acces'},summary:{en:'What is opened, noticed and available for processing.',ro:'Ce este deschis, observat și disponibil procesării.'},children:[{en:'Presentation and framing',ro:'Prezentare și framing'},{en:'Emotion and salience',ro:'Emoție și saliență'},{en:'Access gate',ro:'Poartă de acces'}]},
 {id:'memory',group:'cognition',label:{en:'Memory and familiarity',ro:'Memorie și familiaritate'},summary:{en:'What becomes familiar, retained or retrievable later.',ro:'Ce devine familiar, este reținut sau poate fi reactualizat ulterior.'},children:[{en:'Familiarity',ro:'Familiaritate'},{en:'Memory retrieval',ro:'Reactualizarea memoriei'},{en:'Correction accessibility',ro:'Accesibilitatea corecției'}]},
 {id:'world',group:'cognition',label:{en:'Priors and world model',ro:'Priors și world model'},summary:{en:'How prior knowledge and new observations form a working internal representation.',ro:'Cum cunoașterea anterioară și observațiile noi formează o reprezentare internă de lucru.'},children:[{en:'Prior knowledge',ro:'Cunoaștere anterioară'},{en:'Internal world model',ro:'Model intern al realității'},{en:'Reassessment',ro:'Reevaluare'}]},
 {id:'appraisal',group:'cognition',label:{en:'Appraisal and uncertainty',ro:'Evaluare și incertitudine'},summary:{en:'How evidence, plausibility and unresolved alternatives are evaluated.',ro:'Cum sunt evaluate dovezile, plauzibilitatea și alternativele nerezolvate.'},children:[{en:'Appraisal',ro:'Evaluare'},{en:'Uncertainty',ro:'Incertitudine'},{en:'Source credibility cues',ro:'Indicii de credibilitate a sursei'}]},
 {id:'belief',group:'cognition',label:{en:'Belief and judgment',ro:'Credință și judecată'},summary:{en:'How an interpretation becomes a truth judgment or task-specific decision.',ro:'Cum devine o interpretare judecată de adevăr sau decizie specifică sarcinii.'},children:[{en:'Belief judgment',ro:'Judecată de credință'},{en:'Judgment and decision',ro:'Judecată și decizie'},{en:'Attention to accuracy',ro:'Atenție la acuratețe'}]},
 {id:'social',group:'social-action',label:{en:'Social context',ro:'Context social'},summary:{en:'How norms, apparent consensus and social incentives interact with interpretation.',ro:'Cum interacționează normele, consensul aparent și stimulentele sociale cu interpretarea.'},children:[{en:'Descriptive norms',ro:'Norme descriptive'},{en:'Injunctive norms',ro:'Norme injunctive'},{en:'Group / identity cues',ro:'Indicii de grup / identitate'}]},
 {id:'action',group:'social-action',label:{en:'Action and sharing',ro:'Acțiune și distribuire'},summary:{en:'How decisions become sharing, information seeking or other behavior.',ro:'Cum devin deciziile distribuire, căutare de informații sau alt comportament.'},children:[{en:'Sharing',ro:'Distribuire'},{en:'Information seeking',ro:'Căutare de informații'},{en:'Downstream exposure',ro:'Expunere ulterioară'}]},
];

export function mountAtlas(host:HTMLElement,language:Language){
 let group='all';let zoom=1;
 const t=(value:Text)=>value[language];
 host.innerHTML=`<section class="atlas-shell"><div class="section-heading"><div><p class="eyebrow">${language==='ro'?'FULL MODEL ATLAS · SECUNDAR':'FULL MODEL ATLAS · SECONDARY'}</p><h2>${language==='ro'?'Vedere macro a CBD':'CBD macro-process view'}</h2><p>${language==='ro'?'Atlasul nu este pagina de pornire. Arată implicit numai macro-procesele; submecanismele apar la cerere.':'The Atlas is not the starting page. It shows only macro-processes by default; submechanisms appear on demand.'}</p></div></div><div class="panel atlas-controls"><label>${language==='ro'?'Filtru':'Filter'} <select id="atlas-filter"><option value="all">${language==='ro'?'Toate macro-procesele':'All macro-processes'}</option><option value="environment">${language==='ro'?'Mediu informațional':'Information environment'}</option><option value="cognition">${language==='ro'?'Procesare cognitivă':'Cognitive processing'}</option><option value="social-action">${language==='ro'?'Social și acțiune':'Social & action'}</option></select></label><div><button class="secondary-button" type="button" data-atlas-zoom="out" aria-label="Zoom out">−</button><span id="atlas-zoom-label">100%</span><button class="secondary-button" type="button" data-atlas-zoom="in" aria-label="Zoom in">+</button></div></div><div class="panel atlas-viewport"><div class="atlas-track" id="atlas-track"></div></div><p class="atlas-boundary">${language==='ro'?'Muchiile complete și submecanismele nu sunt afișate simultan. Atlasul păstrează progressive disclosure pentru a evita un hairball.':'Complete edges and submechanisms are not displayed simultaneously. The Atlas uses progressive disclosure to avoid a hairball.'}</p></section>`;
 const track=host.querySelector<HTMLElement>('#atlas-track')!;const zoomLabel=host.querySelector<HTMLElement>('#atlas-zoom-label')!;
 const render=()=>{
  const visible=stages.filter(stage=>group==='all'||stage.group===group);
  track.style.setProperty('--atlas-zoom',String(zoom));
  track.innerHTML=visible.map((stage,index)=>`<div class="atlas-stage-wrap"><details class="atlas-stage"><summary><span class="atlas-number">${String(index+1).padStart(2,'0')}</span><strong>${t(stage.label)}</strong><p>${t(stage.summary)}</p><span class="atlas-expand">${language==='ro'?'+ submecanisme':'+ submechanisms'}</span></summary><ul>${stage.children.map(child=>`<li>${t(child)}</li>`).join('')}</ul></details>${index<visible.length-1?'<span class="atlas-arrow" aria-hidden="true">→</span>':''}</div>`).join('');
  zoomLabel.textContent=`${Math.round(zoom*100)}%`;
 };
 host.querySelector<HTMLSelectElement>('#atlas-filter')!.onchange=event=>{group=(event.currentTarget as HTMLSelectElement).value;render();};
 host.querySelectorAll<HTMLButtonElement>('[data-atlas-zoom]').forEach(button=>button.onclick=()=>{zoom=Math.min(1.25,Math.max(.75,zoom+(button.dataset.atlasZoom==='in'?.1:-.1)));render();});
 render();
}
