import './style.css';
import {productCopy,relationStatusLabels,t,type Language,type RelationStatus} from './content';
import {interventions,type InterventionCard} from './interventions';
import {mechanismMap,pathwayGroups,pathwayMap,pathways,type ProductMechanism,type ProductPathway} from './pathways';
import {mountTheory} from './theory';
import {mountAtlas} from './atlas';

type View='explore'|'theory'|'interventions'|'atlas';
type State={language:Language;view:View;pathwayId:string|null;mechanismId:string|null;theorySlug?:string};

const app=document.querySelector<HTMLDivElement>('#app')!;
const savedLanguage=localStorage.getItem('cem.product.language');
const state:State={language:savedLanguage==='ro'?'ro':'en',view:'explore',pathwayId:null,mechanismId:null};
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const txt=(value:{en:string;ro:string})=>esc(t(value,state.language));
const currentPath=()=>state.pathwayId?pathwayMap.get(state.pathwayId)??null:null;

function header():string{
 const nav=(view:View,label:string,secondary=false)=>`<button type="button" data-view="${view}" aria-pressed="${state.view===view}" ${secondary?'class="secondary-destination"':''}>${label}</button>`;
 return `<a class="skip-link" href="#main">${state.language==='ro'?'Sari la conținut':'Skip to content'}</a><header class="product-header"><div class="brand"><img src="./icon.svg" alt=""/><div><h1>${txt(productCopy.title)}</h1><p>${txt(productCopy.subtitle)}</p></div></div><nav class="header-nav" aria-label="${state.language==='ro'?'Secțiuni':'Sections'}">${nav('explore',state.language==='ro'?'Explorează':'Explore')}${nav('theory',txt(productCopy.theory))}${nav('interventions',txt(productCopy.interventions))}${nav('atlas',state.language==='ro'?'Atlas complet':'Full Atlas',true)}</nav><div class="language-switch" role="group" aria-label="Language"><button type="button" data-lang="en" aria-pressed="${state.language==='en'}">EN</button><button type="button" data-lang="ro" aria-pressed="${state.language==='ro'}">RO</button></div></header>`;
}

function questionPanel():string{
 return `<section class="panel question-panel" aria-labelledby="question-heading"><div class="section-heading"><div><p class="eyebrow">${state.language==='ro'?'ÎNTREBĂRI / FENOMENE':'QUESTIONS / PHENOMENA'}</p><h2 id="question-heading">${state.language==='ro'?'De unde vrei să începi?':'Where do you want to start?'}</h2><p>${state.language==='ro'?'Alege fenomenul, nu registry-ul. Fiecare întrebare deschide numai mecanismele necesare și păstrează restul modelului în fundal.':'Choose a phenomenon, not the registry. Each question opens only the mechanisms needed and keeps the rest of the model in the background.'}</p></div></div><div class="question-groups">${pathwayGroups.map(([group,label])=>`<section class="question-group"><h3>${txt(label)}</h3><div class="question-grid question-grid-expanded">${pathways.filter(path=>path.group===group).map(path=>`<button type="button" class="question-card ${state.pathwayId===path.id?'is-selected':''}" data-question="${path.id}" aria-pressed="${state.pathwayId===path.id}"><strong>${txt(path.question)}</strong><span>${state.language==='ro'?'Explorează traseul':'Explore pathway'} →</span></button>`).join('')}</div></section>`).join('')}</div></section>`;
}

function edge(path:ProductPathway,index:number):string{
 const relation=path.edges[index];const statusLabel=relationStatusLabels[relation.status as RelationStatus];
 return `<div class="path-edge" aria-label="${esc(`${t(statusLabel,state.language)}. ${t(relation.note,state.language)}`)}"><div class="edge-line" aria-hidden="true"></div><span class="edge-status" data-status="${relation.status}">${txt(statusLabel)}</span><button class="edge-help" type="button" title="${txt(relation.note)}" aria-label="${state.language==='ro'?'Explicația statutului legăturii':'Explain relation status'}">?</button></div>`;
}

function pathwayView(path:ProductPathway):string{
 const nodes=path.mechanismIds.map((id,index)=>{const mechanism=mechanismMap.get(id)!;const node=`<button type="button" class="path-node" data-mechanism="${esc(id)}"><span class="step">${String(index+1).padStart(2,'0')}</span><div><strong>${txt(mechanism.label)}</strong><p>${txt(mechanism.short)}</p></div><span class="open-hint">${state.language==='ro'?'Detalii + dovezi':'Details + evidence'} →</span></button>`;return index===path.mechanismIds.length-1?node:`${node}${edge(path,index)}`;}).join('');
 return `<section class="pathway-section" aria-labelledby="pathway-heading"><div class="panel pathway-panel"><div class="section-heading"><div><p class="eyebrow">PATHWAY EXPLORER</p><h2 id="pathway-heading">${txt(path.title)}</h2><p>${txt(path.intro)}</p></div><button class="secondary-button" type="button" data-open-path-theory>${state.language==='ro'?'Citește teoria':'Read theory'}</button></div><div class="pathway-row path-count-${path.mechanismIds.length}" data-pathway="${path.id}">${nodes}</div><div class="secondary" aria-label="${state.language==='ro'?'Factori secundari':'Secondary factors'}">${path.secondary.map(item=>`<details><summary>+ ${txt(item.label)}</summary><p>${txt(item.text)}</p></details>`).join('')}</div></div></section>`;
}

function insightStrip(path:ProductPathway):string{
 const cards=[{title:{en:'Strongest evidence',ro:'Cele mai puternice dovezi'},body:path.strongest},{title:{en:'Main uncertainty',ro:'Incertitudinea principală'},body:path.uncertainty},{title:{en:'Important moderators',ro:'Moderatori importanți'},body:path.moderators},{title:{en:'What CEM cannot claim',ro:'Ce nu poate afirma CEM'},body:path.cannot}];
 return `<section class="insight-section" aria-labelledby="insight-heading"><div class="panel"><div class="section-heading"><div><p class="eyebrow">${state.language==='ro'?'CE CONTEAZĂ PENTRU ACEST TRASEU':'WHAT MATTERS FOR THIS PATHWAY'}</p><h2 id="insight-heading">${state.language==='ro'?'Dovezi, incertitudine și limite':'Evidence, uncertainty and limits'}</h2></div><button type="button" class="secondary-button" data-view="interventions">${txt(productCopy.interventions)}</button></div><div class="insight-grid">${cards.map(card=>`<article class="insight-card"><h3>${txt(card.title)}</h3><p>${txt(card.body)}</p></article>`).join('')}</div></div></section>`;
}

function exploreView():string{
 const path=currentPath();
 return `<div class="full-view" data-active="true" data-product-view="explore"><section class="hero"><p class="eyebrow">COGNITIVE EPISTEMIC MODEL</p><h2>${state.language==='ro'?'Prin ce mecanisme poate informația să ajungă să schimbe ceea ce credem și facem?':'Through what mechanisms can information end up changing what we believe and do?'}</h2><p>${txt(productCopy.intro)}</p></section>${questionPanel()}${path?pathwayView(path)+insightStrip(path):`<section class="empty-prompt" aria-live="polite"><span>↓</span><p>${state.language==='ro'?'Alege o întrebare pentru a vedea traseul relevant.':'Choose a question to reveal the relevant pathway.'}</p></section>`}</div>`;
}

function theoryView():string{return `<div class="full-view" data-active="true" data-product-view="theory"><section class="hero compact-hero"><p class="eyebrow">${txt(productCopy.theory)}</p><h2>${state.language==='ro'?'Manualul complet CEM':'The complete CEM manual'}</h2><p>${state.language==='ro'?'Cuprins, căutare, glosar, citări și legături contextuale. Reader-ul public transformă identificatorii tehnici în limbaj natural.':'Contents, search, glossary, citations and contextual links. The public reader translates technical identifiers into natural language.'}</p></section><div id="theory-v2-host" aria-busy="true"></div></div>`;}

function interventionCard(item:InterventionCard,relevant:boolean){return `<article class="intervention-card ${relevant?'is-relevant':''}" data-intervention="${item.id}">${relevant?`<span class="relevance-flag">${state.language==='ro'?'RELEVANT PENTRU TRASEU':'RELEVANT TO PATHWAY'}</span>`:''}<h3>${txt(item.label)}</h3><dl><div><dt>${state.language==='ro'?'Mecanism țintă':'Target mechanism'}</dt><dd>${txt(item.target)}</dd></div><div><dt>Evidence</dt><dd>${txt(item.evidence)}</dd></div><div><dt>Outcome</dt><dd>${txt(item.outcome)}</dd></div><div><dt>Effect</dt><dd>${txt(item.effect)}</dd></div><div><dt>${state.language==='ro'?'Populație / context':'Population / context'}</dt><dd>${txt(item.context)}</dd></div><div><dt>${state.language==='ro'?'Moderatori':'Moderators'}</dt><dd>${txt(item.moderators)}</dd></div><div><dt>${state.language==='ro'?'Durabilitate':'Durability'}</dt><dd>${txt(item.duration)}</dd></div><div><dt>${state.language==='ro'?'Trade-offs / efecte nedorite':'Trade-offs / adverse effects'}</dt><dd>${txt(item.tradeoffs)}</dd></div><div><dt>${state.language==='ro'?'Limitări':'Limitations'}</dt><dd>${txt(item.limitations)}</dd></div></dl><div class="intervention-sources">${item.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.label)} ↗</a>`).join('')}</div></article>`;}

function interventionsView():string{
 const path=currentPath();const relevant=new Set(path?.interventionIds??[]);const ordered=[...interventions].sort((a,b)=>Number(relevant.has(b.id))-Number(relevant.has(a.id)));
 return `<div class="full-view" data-active="true" data-product-view="interventions"><section class="hero compact-hero"><p class="eyebrow">${txt(productCopy.interventions)}</p><h2>${state.language==='ro'?'Ce intervenții au fost testate și ce rezultate au avut?':'Which interventions have been tested and what happened?'}</h2><p>${state.language==='ro'?'Intervention Explorer prezintă dovezi, nu recomandări normative. Efectele trebuie citite în contextul outcome-ului, populației și designului studiat.':'Intervention Explorer presents evidence, not normative recommendations. Effects must be read in the context of the studied outcome, population and design.'}</p></section>${path?`<div class="path-context-note"><strong>${state.language==='ro'?'Traseu curent:':'Current pathway:'}</strong> ${txt(path.question)}</div>`:''}<section class="intervention-grid intervention-grid-expanded">${ordered.map(item=>interventionCard(item,relevant.has(item.id))).join('')}</section><p class="nonprescriptive">${state.language==='ro'?'CEM nu selectează automat o intervenție „corectă”. Unele clase au meta-analize robuste pentru outcome-uri specifice; altele au dovezi mai timpurii sau dependente de context.':'CEM does not automatically select a “correct” intervention. Some classes have robust meta-analyses for specific outcomes; others have earlier or more context-dependent evidence.'}</p></div>`;
}

function atlasView():string{return `<div class="full-view" data-active="true" data-product-view="atlas"><section class="hero compact-hero"><p class="eyebrow">${state.language==='ro'?'VEDERE SECUNDARĂ':'SECONDARY VIEW'}</p><h2>${state.language==='ro'?'Atlasul complet al modelului':'Full Model Atlas'}</h2><p>${state.language==='ro'?'Folosește Atlasul numai când ai nevoie de orientare la nivelul întregului sistem. Pathway Explorer rămâne obiectul principal al produsului.':'Use the Atlas only when you need system-wide orientation. Pathway Explorer remains the primary product object.'}</p></section><div id="atlas-v2-host"></div></div>`;}

function drawerShell(){return `<div class="context-backdrop" data-open="false" id="context-backdrop"></div><aside class="context-drawer" data-open="false" id="context-drawer" aria-hidden="true" aria-label="${state.language==='ro'?'Detalii mecanism':'Mechanism details'}"></aside>`;}
function mechanismDrawer(mechanism:ProductMechanism){
 const drawer=document.querySelector<HTMLElement>('#context-drawer')!;const backdrop=document.querySelector<HTMLElement>('#context-backdrop')!;
 drawer.innerHTML=`<div class="drawer-header"><div><p class="eyebrow">${state.language==='ro'?'MECANISM SELECTAT':'SELECTED MECHANISM'}</p><h2>${txt(mechanism.label)}</h2></div><button type="button" class="drawer-close" data-close-drawer>${txt(productCopy.close)}</button></div><div class="drawer-body"><section class="detail-block"><h3>WHAT IS IT?</h3><p>${txt(mechanism.what)}</p></section><section class="detail-block"><h3>WHY DOES IT MATTER?</h3><p>${txt(mechanism.why)}</p></section><section class="detail-block"><h3>WHAT INFLUENCES IT?</h3><ul>${mechanism.influencedBy.map(item=>`<li>${txt(item)}</li>`).join('')}</ul></section><section class="detail-block"><h3>WHAT DOES IT INFLUENCE?</h3><ul>${mechanism.influences.map(item=>`<li>${txt(item)}</li>`).join('')}</ul></section><section class="detail-block"><h3>WHAT DOES THE EVIDENCE SAY?</h3><p>${txt(mechanism.evidence)}</p></section>${mechanism.effect?`<section class="detail-block effect-callout"><h3>HOW LARGE IS THE EFFECT?</h3><p>${txt(mechanism.effect)}</p></section>`:''}<section class="detail-block"><h3>WHEN DOES IT CHANGE?</h3><p>${txt(mechanism.conditions)}</p></section><section class="detail-block"><h3>WHAT ELSE COULD EXPLAIN IT?</h3><p>${txt(mechanism.competing)}</p></section><section class="detail-block"><h3>WHAT ARE THE LIMITATIONS?</h3><p>${txt(mechanism.limitations)}</p></section><section class="detail-block"><h3>INTERVENTIONS STUDIED</h3><p>${txt(mechanism.interventions)}</p></section>${mechanism.sources.length?`<section class="detail-block"><h3>${state.language==='ro'?'SURSE PRINCIPALE':'KEY SOURCES'}</h3><div class="drawer-sources">${mechanism.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.label)} ↗</a>`).join('')}</div></section>`:''}<div class="drawer-actions"><button type="button" class="primary-button" data-open-theory>${state.language==='ro'?'Citește teoria completă':'Read full theory'}</button><button type="button" class="secondary-button" data-open-interventions>${txt(productCopy.interventions)}</button></div></div>`;
 drawer.dataset.open='true';drawer.setAttribute('aria-hidden','false');backdrop.dataset.open='true';
 const close=()=>{drawer.dataset.open='false';drawer.setAttribute('aria-hidden','true');backdrop.dataset.open='false';state.mechanismId=null;};drawer.querySelector<HTMLButtonElement>('[data-close-drawer]')!.onclick=close;backdrop.onclick=close;
 drawer.querySelector<HTMLButtonElement>('[data-open-theory]')!.onclick=()=>{state.theorySlug=mechanism.theorySlug;close();state.view='theory';render();};drawer.querySelector<HTMLButtonElement>('[data-open-interventions]')!.onclick=()=>{close();state.view='interventions';render();};drawer.querySelector<HTMLButtonElement>('[data-close-drawer]')!.focus();
}

function footer(){return `<footer class="product-footer"><span>InfoClar Model Suite · Cognitive Epistemic Model</span><span>${state.language==='ro'?'Modelul științific, M1 și MOD.14 rămân neschimbate':'Scientific model, M1 and MOD.14 remain unchanged'}</span></footer>`;}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(button=>button.onclick=()=>{state.language=button.dataset.lang as Language;localStorage.setItem('cem.product.language',state.language);render();});document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view as View;render();});document.querySelectorAll<HTMLButtonElement>('[data-question]').forEach(button=>button.onclick=()=>{state.pathwayId=button.dataset.question!;state.view='explore';render();document.querySelector('#pathway-heading')?.scrollIntoView({block:'start',behavior:'smooth'});});document.querySelectorAll<HTMLButtonElement>('[data-mechanism]').forEach(button=>button.onclick=()=>{const mechanism=mechanismMap.get(button.dataset.mechanism!)!;state.mechanismId=mechanism.id;mechanismDrawer(mechanism);});document.querySelector<HTMLButtonElement>('[data-open-path-theory]')?.addEventListener('click',()=>{state.theorySlug=currentPath()?.theorySlugs[0];state.view='theory';render();});}
async function mountAsyncViews(){if(state.view==='theory'){const host=document.querySelector<HTMLElement>('#theory-v2-host')!;try{await mountTheory(host,{language:state.language,initialSlug:state.theorySlug,onBack:()=>{state.view='explore';render();}});host.setAttribute('aria-busy','false');}catch(error){host.innerHTML=`<div class="panel"><h3>${state.language==='ro'?'Teoria nu poate fi încărcată':'Theory could not be loaded'}</h3><p>${esc(String(error))}</p></div>`;}}if(state.view==='atlas')mountAtlas(document.querySelector<HTMLElement>('#atlas-v2-host')!,state.language);}
function render(){document.documentElement.lang=state.language;const view=state.view==='explore'?exploreView():state.view==='theory'?theoryView():state.view==='interventions'?interventionsView():atlasView();app.innerHTML=`${header()}<main id="main" class="product-main" tabindex="-1">${view}${drawerShell()}${footer()}</main>`;bind();void mountAsyncViews();}
render();
