import './style.css';
import './question-expansion.css';
import {productCopy,relationStatusLabels,t,type Language,type RelationStatus} from './content';
import {interventions,type InterventionCard} from './interventions';
import {mechanismMap,pathwayGroups,pathwayMap,pathways,type ProductMechanism,type ProductPathway} from './pathways';
import {mountTheory} from './theory';
import {mountAtlas} from './atlas';

type View='explore'|'theory'|'interventions'|'atlas';
type State={language:Language;view:View;pathwayId:string|null;mechanismId:string|null;theorySlug?:string};

const app=document.querySelector<HTMLDivElement>('#app')!;
const savedLanguage=localStorage.getItem('cem.product.language');
const state:State={language:savedLanguage==='ro'?'ro':'en',view:'explore',pathwayId:null,mechanismId:null};
const featuredPathwayId='repetition';
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char]!));
const txt=(value:{en:string;ro:string})=>esc(t(value,state.language));
const currentPath=()=>state.pathwayId?pathwayMap.get(state.pathwayId)??null:null;
const ui=(en:string,ro:string)=>state.language==='ro'?ro:en;

function header():string{
 const nav=(view:View,label:string,secondary=false)=>`<button type="button" data-view="${view}" aria-pressed="${state.view===view}" ${secondary?'class="secondary-destination"':''}>${label}</button>`;
 return `<a class="skip-link" href="#main">${ui('Skip to content','Sari la conținut')}</a><header class="product-header"><div class="brand"><img src="./icon.png" alt=""/><div><h1>${txt(productCopy.title)}</h1><p>${txt(productCopy.subtitle)}</p></div></div><nav class="header-nav" aria-label="${ui('Sections','Secțiuni')}">${nav('explore',ui('Explore','Explorează'))}${nav('theory',txt(productCopy.theory))}${nav('interventions',txt(productCopy.interventions))}${nav('atlas',ui('Full Atlas','Atlas complet'),true)}</nav><div class="language-switch" role="group" aria-label="Language"><button type="button" data-lang="en" aria-pressed="${state.language==='en'}">EN</button><button type="button" data-lang="ro" aria-pressed="${state.language==='ro'}">RO</button></div></header>`;
}

function questionPanel():string{
 const featured=pathwayMap.get(featuredPathwayId)!;
 const groups=pathwayGroups.map(([group,label])=>{const choices=pathways.filter(path=>path.group===group&&path.id!==featuredPathwayId);if(!choices.length)return '';return `<section class="future-question-group"><h4>${txt(label)}</h4><ul class="future-question-list">${choices.map(path=>`<li><button type="button" class="future-question-button ${state.pathwayId===path.id?'is-selected':''}" data-question="${path.id}" aria-pressed="${state.pathwayId===path.id}"><strong>${txt(path.question)}</strong><span>${ui('Explore pathway','Explorează traseul')} →</span></button></li>`).join('')}</ul></section>`;}).join('');
 return `<section class="panel question-panel" aria-labelledby="question-heading"><div class="section-heading"><div><p class="eyebrow">${ui('START WITH A HUMAN QUESTION','PORNEȘTE DE LA O ÎNTREBARE UMANĂ')}</p><h2 id="question-heading">${ui('What do you want to understand?','Ce vrei să înțelegi?')}</h2><p>${ui('Choose a question. CBD opens the shortest evidence-grounded pathway it can justify, then lets you inspect each step, relation, uncertainty and limitation.','Alege o întrebare. CBD deschide cel mai scurt traseu susținut de dovezi pe care îl poate justifica, apoi îți permite să inspectezi fiecare pas, relație, incertitudine și limitare.')}</p></div></div><div class="prototype-question-wrap"><button type="button" class="question-card prototype-question ${state.pathwayId===featured.id?'is-selected':''}" data-question="${featured.id}" aria-pressed="${state.pathwayId===featured.id}"><span class="prototype-badge">${ui('FEATURED STARTING QUESTION','ÎNTREBARE RECOMANDATĂ PENTRU ÎNCEPUT')}</span><strong>${txt(featured.question)}</strong><span>${ui('Explore the pathway','Explorează traseul')} →</span></button></div><details class="future-questions"><summary>${ui('More evidence-grounded questions CBD can examine','Alte întrebări bazate pe dovezi pe care CBD le poate examina')}</summary><p>${ui('Choose any question below. Each opens a compact pathway and keeps detailed evidence on demand.','Alege oricare dintre întrebările de mai jos. Fiecare deschide un traseu compact și păstrează dovezile detaliate la cerere.')}</p><div class="future-question-groups">${groups}</div></details></section>`;
}

function edge(path:ProductPathway,index:number):string{
 const relation=path.edges[index];const statusLabel=relationStatusLabels[relation.status as RelationStatus];const explanation=`${t(statusLabel,state.language)}. ${t(relation.note,state.language)}`;
 return `<div class="path-edge" data-status="${relation.status}" aria-label="${esc(explanation)}"><div class="edge-line" data-status="${relation.status}" aria-hidden="true"></div><button class="edge-help" data-status="${relation.status}" type="button" title="${esc(explanation)}" aria-label="${ui('Explain this relationship','Explică această relație')}: ${esc(explanation)}"><span aria-hidden="true">i</span></button></div>`;
}

function relationLegend(path:ProductPathway):string{
 const statuses=[...new Set(path.edges.map(item=>item.status))];
 return `<div class="relation-legend" aria-label="${ui('Relationship evidence key','Legendă pentru tipul relațiilor')}"><span class="relation-legend-label">${ui('RELATION KEY','LEGENDA RELAȚIILOR')}</span>${statuses.map(status=>`<span class="relation-key" data-status="${status}"><i aria-hidden="true"></i>${txt(relationStatusLabels[status])}</span>`).join('')}<span class="relation-legend-help">${ui('Hover or focus the small i between steps for the evidence boundary.','Treci cu cursorul sau focalizează micul i dintre pași pentru limita dovezii.')}</span></div>`;
}

function pathwayView(path:ProductPathway):string{
 const nodes=path.mechanismIds.map((id,index)=>{const mechanism=mechanismMap.get(id)!;const node=`<button type="button" class="path-node" data-mechanism="${esc(id)}"><span class="step">${String(index+1).padStart(2,'0')}</span><div><strong>${txt(mechanism.label)}</strong><p>${txt(mechanism.short)}</p></div><span class="open-hint">${ui('Details + evidence','Detalii + dovezi')} →</span></button>`;return index===path.mechanismIds.length-1?node:`${node}${edge(path,index)}`;}).join('');
 return `<section class="pathway-section" aria-labelledby="pathway-heading"><div class="panel pathway-panel"><div class="section-heading"><div><p class="eyebrow">MECHANISM EXPLORER</p><h2 id="pathway-heading">${txt(path.title)}</h2><p>${txt(path.intro)}</p></div><button class="secondary-button" type="button" data-open-path-theory>${ui('Read theory','Citește teoria')}</button></div><div class="pathway-flow-cue" aria-hidden="true"><span>CAUSE</span><b>→</b><span>MECHANISM</span><b>→</b><span>EFFECT</span><b>→</b><span>ACTION</span></div><div class="pathway-row path-count-${path.mechanismIds.length}" data-pathway="${path.id}">${nodes}</div>${relationLegend(path)}<div class="secondary" aria-label="${ui('Secondary factors','Factori secundari')}">${path.secondary.map(item=>`<details><summary>+ ${txt(item.label)}</summary><p>${txt(item.text)}</p></details>`).join('')}</div></div></section>`;
}

function insightStrip(path:ProductPathway):string{
 const cards=[{title:{en:'Strongest evidence',ro:'Cele mai puternice dovezi'},body:path.strongest},{title:{en:'Main uncertainty',ro:'Incertitudinea principală'},body:path.uncertainty},{title:{en:'Important moderators',ro:'Moderatori importanți'},body:path.moderators},{title:{en:'What CBD cannot claim',ro:'Ce nu poate afirma CBD'},body:path.cannot}];
 return `<section class="insight-section" aria-labelledby="insight-heading"><div class="panel"><div class="section-heading"><div><p class="eyebrow">${ui('WHAT MATTERS FOR THIS PATHWAY','CE CONTEAZĂ PENTRU ACEST TRASEU')}</p><h2 id="insight-heading">${ui('Evidence, uncertainty and limits','Dovezi, incertitudine și limite')}</h2></div><button type="button" class="secondary-button" data-view="interventions">${txt(productCopy.interventions)}</button></div><div class="insight-grid">${cards.map(card=>`<article class="insight-card"><h3>${txt(card.title)}</h3><p>${txt(card.body)}</p></article>`).join('')}</div></div></section>`;
}

function exploreView():string{
 const path=currentPath();
 return `<div class="full-view" data-active="true" data-product-view="explore"><section class="hero"><p class="eyebrow">COGNITIVE EPISTEMIC MODEL</p><h2>${ui('How can information influence what we believe and do?','Cum poate informația influența ceea ce credem și facem?')}</h2><p>${txt(productCopy.intro)}</p></section>${questionPanel()}${path?pathwayView(path)+insightStrip(path):`<section class="empty-prompt" aria-live="polite"><span>↓</span><p>${ui('Choose a question to reveal its mechanism pathway.','Alege o întrebare pentru a vedea traseul mecanismelor.')}</p></section>`}</div>`;
}

function theoryView():string{return `<div class="full-view" data-active="true" data-product-view="theory"><section class="hero compact-hero"><p class="eyebrow">${txt(productCopy.theory)}</p><h2>${ui('The complete CBD manual','Manualul complet CBD')}</h2><p>${ui('Contents, search, glossary, citations and contextual links. The public reader translates implementation identifiers into natural language.','Cuprins, căutare, glosar, citări și legături contextuale. Reader-ul public traduce identificatorii de implementare în limbaj natural.')}</p></section><div id="theory-v2-host" aria-busy="true"></div></div>`;}

function interventionCard(item:InterventionCard,relevant:boolean){return `<article class="intervention-card ${relevant?'is-relevant':''}" data-intervention="${item.id}">${relevant?`<span class="relevance-flag">${ui('RELEVANT TO PATHWAY','RELEVANT PENTRU TRASEU')}</span>`:''}<h3>${txt(item.label)}</h3><dl><div><dt>${ui('Target mechanism','Mecanism țintă')}</dt><dd>${txt(item.target)}</dd></div><div><dt>${ui('Evidence','Dovezi')}</dt><dd>${txt(item.evidence)}</dd></div><div><dt>${ui('Outcome','Rezultat')}</dt><dd>${txt(item.outcome)}</dd></div><div><dt>${ui('Effect','Efect')}</dt><dd>${txt(item.effect)}</dd></div><div><dt>${ui('Population / context','Populație / context')}</dt><dd>${txt(item.context)}</dd></div><div><dt>${ui('Moderators','Moderatori')}</dt><dd>${txt(item.moderators)}</dd></div><div><dt>${ui('Durability','Durabilitate')}</dt><dd>${txt(item.duration)}</dd></div><div><dt>${ui('Trade-offs / adverse effects','Trade-offs / efecte nedorite')}</dt><dd>${txt(item.tradeoffs)}</dd></div><div><dt>${ui('Limitations','Limitări')}</dt><dd>${txt(item.limitations)}</dd></div></dl><div class="intervention-sources">${item.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.label)} ↗</a>`).join('')}</div></article>`;}

function interventionsView():string{
 const path=currentPath();
 if(!path)return `<div class="full-view" data-active="true" data-product-view="interventions"><section class="hero compact-hero"><p class="eyebrow">${txt(productCopy.interventions)}</p><h2>${ui('Interventions stay attached to a mechanism pathway','Intervențiile rămân legate de un traseu mecanistic')}</h2><p>${ui('CBD presents evidence about studied interventions rather than a generic recommendation catalogue.','CBD prezintă dovezi despre intervențiile studiate, nu un catalog generic de recomandări.')}</p></section><section class="panel select-path-prompt"><h3>${ui('Choose a question first','Alege mai întâi o întrebare')}</h3><p>${ui('The intervention view will then show only the intervention classes relevant to that pathway.','Vederea intervențiilor va afișa apoi numai clasele relevante pentru acel traseu.')}</p><button type="button" class="primary-button" data-view="explore">${ui('Go to the questions','Mergi la întrebări')}</button></section></div>`;
 const relevant=new Set(path.interventionIds);const ordered=interventions.filter(item=>relevant.has(item.id));
 return `<div class="full-view" data-active="true" data-product-view="interventions"><section class="hero compact-hero"><p class="eyebrow">${txt(productCopy.interventions)}</p><h2>${ui('Which interventions have been tested and what happened?','Ce intervenții au fost testate și ce rezultate au avut?')}</h2><p>${ui('Intervention Explorer presents evidence, not normative recommendations. Effects must be read in the context of the studied outcome, population and design.','Intervention Explorer prezintă dovezi, nu recomandări normative. Efectele trebuie citite în contextul rezultatului, populației și designului studiat.')}</p></section><div class="path-context-note"><strong>${ui('Current pathway:','Traseu curent:')}</strong> ${txt(path.question)}</div><section class="intervention-grid intervention-grid-expanded">${ordered.map(item=>interventionCard(item,true)).join('')}</section><p class="nonprescriptive">${ui('CBD does not automatically select a “correct” intervention. The cards report what was studied, for which outcome and with which limitations.','CBD nu selectează automat o intervenție „corectă”. Cardurile arată ce a fost studiat, pentru ce rezultat și cu ce limitări.')}</p></div>`;
}

function atlasView():string{return `<div class="full-view" data-active="true" data-product-view="atlas"><section class="hero compact-hero"><p class="eyebrow">${ui('SECONDARY VIEW','VEDERE SECUNDARĂ')}</p><h2>${ui('Full Model Atlas','Atlasul complet al modelului')}</h2><p>${ui('Use the Atlas only when you need system-wide orientation. Mechanism Explorer remains the primary product object.','Folosește Atlasul numai când ai nevoie de orientare la nivelul întregului sistem. Mechanism Explorer rămâne obiectul principal al produsului.')}</p></section><div id="atlas-v2-host"></div></div>`;}

function drawerShell(){return `<div class="context-backdrop" data-open="false" id="context-backdrop"></div><aside class="context-drawer" data-open="false" id="context-drawer" role="dialog" aria-modal="true" aria-hidden="true" aria-label="${ui('Mechanism details','Detalii mecanism')}"></aside>`;}
function mechanismDrawer(mechanism:ProductMechanism){
 const drawer=document.querySelector<HTMLElement>('#context-drawer')!;const backdrop=document.querySelector<HTMLElement>('#context-backdrop')!;const opener=document.activeElement instanceof HTMLElement?document.activeElement:null;
 drawer.innerHTML=`<div class="drawer-header"><div><p class="eyebrow">${ui('SELECTED MECHANISM','MECANISM SELECTAT')}</p><h2>${txt(mechanism.label)}</h2></div><button type="button" class="drawer-close" data-close-drawer>${txt(productCopy.close)}</button></div><div class="drawer-body"><section class="detail-block"><h3>${ui('WHAT IS IT?','CE ESTE?')}</h3><p>${txt(mechanism.what)}</p></section><section class="detail-block"><h3>${ui('WHY DOES IT MATTER?','DE CE CONTEAZĂ?')}</h3><p>${txt(mechanism.why)}</p></section><section class="detail-block"><h3>${ui('WHAT INFLUENCES IT?','CE ÎL INFLUENȚEAZĂ?')}</h3><ul>${mechanism.influencedBy.map(item=>`<li>${txt(item)}</li>`).join('')}</ul></section><section class="detail-block"><h3>${ui('WHAT DOES IT INFLUENCE?','CE INFLUENȚEAZĂ?')}</h3><ul>${mechanism.influences.map(item=>`<li>${txt(item)}</li>`).join('')}</ul></section><section class="detail-block"><h3>${ui('WHAT DOES THE EVIDENCE SAY?','CE SPUN DOVEZILE?')}</h3><p>${txt(mechanism.evidence)}</p></section>${mechanism.effect?`<section class="detail-block effect-callout"><h3>${ui('HOW LARGE IS THE EFFECT?','CÂT DE MARE ESTE EFECTUL?')}</h3><p>${txt(mechanism.effect)}</p></section>`:''}<section class="detail-block"><h3>${ui('WHEN DOES IT CHANGE?','CÂND SE MODIFICĂ?')}</h3><p>${txt(mechanism.conditions)}</p></section><section class="detail-block"><h3>${ui('WHAT ELSE COULD EXPLAIN IT?','CE ALTCEVA L-AR PUTEA EXPLICA?')}</h3><p>${txt(mechanism.competing)}</p></section><section class="detail-block"><h3>${ui('WHAT ARE THE LIMITATIONS?','CARE SUNT LIMITĂRILE?')}</h3><p>${txt(mechanism.limitations)}</p></section><section class="detail-block"><h3>${ui('INTERVENTIONS STUDIED','INTERVENȚII STUDIATE')}</h3><p>${txt(mechanism.interventions)}</p></section>${mechanism.sources.length?`<section class="detail-block"><h3>${ui('KEY SOURCES','SURSE PRINCIPALE')}</h3><div class="drawer-sources">${mechanism.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.label)} ↗</a>`).join('')}</div></section>`:''}<div class="drawer-actions"><button type="button" class="primary-button" data-open-theory>${ui('Read full theory','Citește teoria completă')}</button><button type="button" class="secondary-button" data-open-interventions>${txt(productCopy.interventions)}</button></div></div>`;
 drawer.dataset.open='true';drawer.setAttribute('aria-hidden','false');backdrop.dataset.open='true';
 const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')close();};
 const close=()=>{drawer.dataset.open='false';drawer.setAttribute('aria-hidden','true');backdrop.dataset.open='false';state.mechanismId=null;document.removeEventListener('keydown',onKey);opener?.focus();};
 document.addEventListener('keydown',onKey);drawer.querySelector<HTMLButtonElement>('[data-close-drawer]')!.onclick=close;backdrop.onclick=close;
 drawer.querySelector<HTMLButtonElement>('[data-open-theory]')!.onclick=()=>{state.theorySlug=mechanism.theorySlug;close();state.view='theory';render();};drawer.querySelector<HTMLButtonElement>('[data-open-interventions]')!.onclick=()=>{close();state.view='interventions';render();};drawer.querySelector<HTMLButtonElement>('[data-close-drawer]')!.focus();
}

function footer(){return `<footer class="product-footer"><span>InfoClar Model Suite · Cognitive Belief Dynamics</span></footer>`;}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(button=>button.onclick=()=>{state.language=button.dataset.lang as Language;localStorage.setItem('cem.product.language',state.language);render();});document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view as View;render();});document.querySelectorAll<HTMLButtonElement>('[data-question]').forEach(button=>button.onclick=()=>{state.pathwayId=button.dataset.question!;state.view='explore';render();document.querySelector('#pathway-heading')?.scrollIntoView({block:'start',behavior:'smooth'});});document.querySelectorAll<HTMLButtonElement>('[data-mechanism]').forEach(button=>button.onclick=()=>{const mechanism=mechanismMap.get(button.dataset.mechanism!)!;state.mechanismId=mechanism.id;mechanismDrawer(mechanism);});document.querySelector<HTMLButtonElement>('[data-open-path-theory]')?.addEventListener('click',()=>{state.theorySlug=currentPath()?.theorySlugs[0];state.view='theory';render();});}
async function mountAsyncViews(){if(state.view==='theory'){const host=document.querySelector<HTMLElement>('#theory-v2-host')!;try{await mountTheory(host,{language:state.language,initialSlug:state.theorySlug,onBack:()=>{state.view='explore';render();}});host.setAttribute('aria-busy','false');}catch(error){host.innerHTML=`<div class="panel"><h3>${ui('Theory could not be loaded','Teoria nu poate fi încărcată')}</h3><p>${esc(String(error))}</p></div>`;}}if(state.view==='atlas')mountAtlas(document.querySelector<HTMLElement>('#atlas-v2-host')!,state.language);}
function render(){document.documentElement.lang=state.language;const view=state.view==='explore'?exploreView():state.view==='theory'?theoryView():state.view==='interventions'?interventionsView():atlasView();app.innerHTML=`${header()}<main id="main" class="product-main" tabindex="-1">${view}${drawerShell()}${footer()}</main>`;bind();void mountAsyncViews();}
render();
