from __future__ import annotations

from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator


WORKSPACE_SCHEMA_VERSION = "1"


class WorkspaceError(ValueError):
    pass


def validate_workspace_document(
    document: dict[str, Any],
    *,
    schema_path: str | Path,
    semantic_index: dict[str, Any],
) -> None:
    """Validate one workspace without mutating or migrating it.

    OA-2A deliberately separates validation from future migration logic. Unknown
    schema versions therefore fail closed instead of being rewritten in place.
    """

    schema_path = Path(schema_path)
    import json

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    errors = sorted(
        Draft202012Validator(schema).iter_errors(document),
        key=lambda error: list(error.absolute_path),
    )
    if errors:
        raise WorkspaceError(
            "\n".join(
                f"{'/'.join(str(part) for part in error.absolute_path)}: {error.message}"
                for error in errors
            )
        )

    entity_ids = {item["id"] for item in semantic_index["entities"]}
    relation_ids = {item["id"] for item in semantic_index["relations"]}

    case = document["case"]
    missing_entities = sorted(set(case["entity_refs"]) - entity_ids)
    missing_relations = sorted(set(case["relation_refs"]) - relation_ids)

    focus = case.get("focus", {})
    if focus.get("entity_id") and focus["entity_id"] not in entity_ids:
        missing_entities.append(focus["entity_id"])
    if focus.get("relation_id") and focus["relation_id"] not in relation_ids:
        missing_relations.append(focus["relation_id"])

    for activity in document["provenance"]["activities"]:
        for ref in activity["used"] + activity["generated"]:
            if ref["kind"] == "SEMANTIC_ENTITY" and ref["id"] not in entity_ids:
                missing_entities.append(ref["id"])
            if ref["kind"] == "SEMANTIC_RELATION" and ref["id"] not in relation_ids:
                missing_relations.append(ref["id"])

    if missing_entities:
        raise WorkspaceError(
            f"unresolved workspace semantic entity refs: {sorted(set(missing_entities))}"
        )
    if missing_relations:
        raise WorkspaceError(
            f"unresolved workspace semantic relation refs: {sorted(set(missing_relations))}"
        )

    generated_revisions = {
        ref["id"]
        for activity in document["provenance"]["activities"]
        for ref in activity["generated"]
        if ref["kind"] == "WORKSPACE_REVISION"
    }
    current_revision = document["provenance"]["current_revision_id"]
    if current_revision not in generated_revisions:
        raise WorkspaceError(
            f"current workspace revision was not generated by provenance: {current_revision}"
        )

    for activity in document["provenance"]["activities"]:
        parent = activity.get("revision_of")
        if parent is not None and parent not in generated_revisions:
            raise WorkspaceError(
                f"{activity['id']}: unresolved revision_of workspace revision {parent}"
            )
