import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {buildIndicatorProjection} from '../src/core/indicator-objects.ts';

type Planning={profiles:{id:string;bundles:{mask:number;start:number;false_share:number;true_share:number}[]}[]};
const planning=JSON.parse(await readFile(new URL('../public/model/interventions.json',import.meta.url),'utf8')) as Planning;
const reference=planning.profiles.find(item=>item.id==='reference')!;
const bundle=reference.bundles.find(item=>item.mask===6&&item.start===2)!;

test('OA-7 Indicator objects expose only supported proximal M0 outputs',()=>{const projection=buildIndicatorProjection(bundle);assert.equal(projection.object_type,'IndicatorProjection');assert.equal(projection.persistence,'READ_ONLY_NOT_WORKSPACE');assert.equal(projection.observation_boundary,'SIMULATION_RESULT_IS_NOT_OBSERVED_OUTCOME');assert.equal(projection.indicators.length,2);assert.deepEqual(projection.indicators.map(item=>item.definition.target_stage),['PROXIMAL','PROXIMAL']);assert.deepEqual(projection.indicators.map(item=>item.reading.observation_status),['NOT_OBSERVED','NOT_OBSERVED']);assert.deepEqual(projection.indicators.map(item=>item.reading.reading_kind),['SIMULATION_RESULT','SIMULATION_RESULT']);});
test('OA-7 Indicator objects keep property, procedure and result separate',()=>{const projection=buildIndicatorProjection(bundle);const falseIndicator=projection.indicators.find(item=>item.definition.id==='CEM.INDICATOR.M0.FALSE_SHARING.MEAN13')!;assert.equal(falseIndicator.definition.observed_property,'M0.SIMULATED.FALSE_SHARING.PROBABILITY.MEAN13');assert.equal(falseIndicator.definition.measurement_procedure,'COMPUTED_FROM_M0_FALSE_SHARE_13_STEP_MEAN');assert.equal(falseIndicator.reading.value,bundle.false_share);assert.equal(falseIndicator.reading.unit,'probability');assert.equal('phenomenon_time' in falseIndicator.reading,false);assert.equal('recorded_at' in falseIndicator.reading,false);});
test('OA-7 refuses to fabricate intermediate or final indicators',()=>{const projection=buildIndicatorProjection(bundle);const intermediate=projection.coverage.find(item=>item.stage==='INTERMEDIATE')!;const final=projection.coverage.find(item=>item.stage==='FINAL')!;assert.equal(intermediate.status,'NOT_OPERATIONALIZED');assert.equal(final.status,'NOT_OPERATIONALIZED');assert.deepEqual(intermediate.indicator_ids,[]);assert.deepEqual(final.indicator_ids,[]);});
test('OA-7 indicator definitions remain compatible with the Reality Loop Indicator shape',()=>{const projection=buildIndicatorProjection(bundle);for(const {definition} of projection.indicators){assert.equal(definition.object_type,'Indicator');assert.match(definition.id,/^CEM\.INDICATOR\./);assert(definition.label.ro&&definition.label.en);assert(definition.observed_property);assert.equal(definition.result_type,'NUMBER');assert.equal(definition.unit,'probability');assert(definition.measurement_procedure);assert(definition.source_refs.length>0);assert(definition.limitations.ro&&definition.limitations.en);}});
