export type ProductLang='ro'|'en';
export type EpistemicLevel='EMPIRICAL'|'EXECUTABLE'|'CONCEPTUAL'|'INTERPRETIVE';
export type Bilingual={ro:string;en:string};

export type CemProductNode={
 id:string;
 x:number;
 y:number;
 group:'information'|'representation'|'integration'|'judgment';
 label:Bilingual;
 identifiers:string[];
 summary:Bilingual;
 theory:Bilingual;
 chapterSlug:string;
 statuses:EpistemicLevel[];
 evidenceRefs:string[];
 provenance:Bilingual;
 uncertainty:Bilingual;
 limitation:Bilingual;
};

export type CemProductEdge={
 id:string;
 source:string;
 target:string;
 label:Bilingual;
 level:'EXECUTABLE'|'CONCEPTUAL';
};

export type CemDiagnostic={
 id:string;
 focus:string;
 title:Bilingual;
 why:Bilingual;
 mechanisms:string[];
 evidence:Bilingual;
 uncertainty:Bilingual;
 statuses:EpistemicLevel[];
};

export const cemProductNodes:CemProductNode[]=[
 {id:'available-information',x:7,y:12,group:'information',label:{ro:'Informație disponibilă',en:'Available information'},identifiers:['world / content pool'],summary:{ro:'Totalul informației care ar putea ajunge la agent înainte de selecție, prezentare și acces.',en:'The information that could reach the agent before selection, presentation and access.'},theory:{ro:'CEM separă explicit lumea și informația disponibilă de ceea ce ajunge efectiv să fie observat. Această separare este necesară pentru a nu confunda realitatea cu eșantionul informațional primit de agent.',en:'CEM explicitly separates the world and available information from what is actually observed. This prevents the information sample received by an agent from being mistaken for reality itself.'},chapterSlug:'world-information-representation',statuses:['CONCEPTUAL'],evidenceRefs:[],provenance:{ro:'Originea și completitudinea pool-ului informațional trebuie documentate în orice aplicație empirică.',en:'The origin and completeness of the information pool must be documented in any empirical application.'},uncertainty:{ro:'Informația indisponibilă sau necunoscută nu poate fi inferată din ceea ce a fost observat.',en:'Unavailable or unknown information cannot be inferred from the observed sample.'},limitation:{ro:'Nu este o măsură numerică universală a realității și nu presupune acces complet la lume.',en:'It is not a universal numeric measure of reality and does not assume complete access to the world.'}},
 {id:'selection',x:7,y:35,group:'information',label:{ro:'Selecție editorială',en:'Editorial selection'},identifiers:['Eedit','Vcontent'],summary:{ro:'Determină ce unități dintr-un pool factual fix sunt selectate preferențial pentru prezentare.',en:'Determines which items from a fixed factual pool are preferentially selected for presentation.'},theory:{ro:'M1.E1 separă pool-ul factual de eșantionul editorial observat. Selecția poate modifica distribuția informației întâlnite fără să modifice adevărul evenimentului.',en:'M1.E1 separates the factual pool from the observed editorial sample. Selection can alter the information distribution encountered without changing the truth of the event.'},chapterSlug:'editorial-selection-observed-world',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.TOHIDI.2025'],provenance:{ro:'Politica de selecție și pool-ul de intrare trebuie păstrate separat pentru audit.',en:'The selection policy and input pool must remain separately traceable for audit.'},uncertainty:{ro:'Eedit este o politică de referință, nu un scor măsurat al biasului unei redacții.',en:'Eedit is a reference policy, not a measured newsroom-bias score.'},limitation:{ro:'Nu este o etichetă politică și nu estimează intenția editorului.',en:'It is not a political label and does not estimate editorial intent.'}},
 {id:'presentation',x:7,y:58,group:'information',label:{ro:'Prezentare și framing',en:'Presentation and framing'},identifiers:['Fpres','Gatt'],summary:{ro:'Forma de prezentare poate schimba răspunsul la același conținut semantic.',en:'Presentation form can change responses to semantically equivalent content.'},theory:{ro:'M1.E2 modelează framing-ul confirmation versus refutation și congruența task-specifică fără a transforma framing-ul în factualitate sau ideologie.',en:'M1.E2 models confirmation-versus-refutation framing and task-specific congruence without treating framing as factuality or ideology.'},chapterSlug:'framing-congruence',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.ARUGUETE.2024','REF.ALVARADO.2026'],provenance:{ro:'Condiția de framing și sensul semantic trebuie înregistrate împreună pentru a separa forma de conținut.',en:'Framing condition and semantic meaning must be recorded together to separate form from content.'},uncertainty:{ro:'Efectele sunt dependente de sarcină și populație; coeficienții de referință nu sunt universali.',en:'Effects are task- and population-dependent; reference coefficients are not universal.'},limitation:{ro:'Fpres nu este adevăr, factualitate sau selecție editorială.',en:'Fpres is not truth, factuality or editorial selection.'}},
 {id:'access-gate',x:7,y:81,group:'information',label:{ro:'Acces / poartă de observație',en:'Access / observation gate'},identifiers:['PreviewImpression','Paccess','Access'],summary:{ro:'Separă faptul că un preview a fost disponibil de deschiderea efectivă a conținutului.',en:'Separates preview availability from actually opening the full content.'},theory:{ro:'M1.E3 tratează accesul ca etapă distinctă. Un preview randat nu demonstrează fixație vizuală, lectură, encodare sau înțelegere.',en:'M1.E3 treats access as a distinct stage. A rendered preview does not demonstrate visual fixation, reading, encoding or comprehension.'},chapterSlug:'algorithms-social-feedback',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.ROBERTSON.2023.NEGATIVITY','REF.MATIAS.2021.UPWORTHY'],provenance:{ro:'Impresia de preview și evenimentul de acces trebuie logate separat.',en:'Preview impression and access event must be logged separately.'},uncertainty:{ro:'CEM nu introduce un coeficient generic de atenție; atenția propriu-zisă rămâne nemăsurată fără instrumente dedicate.',en:'CEM does not introduce a generic attention coefficient; attention itself remains unmeasured without dedicated instrumentation.'},limitation:{ro:'Access nu înseamnă atenție, lectură completă, convingere sau aprobare.',en:'Access does not mean attention, completed reading, belief or endorsement.'}},
 {id:'observed-information',x:27,y:14,group:'representation',label:{ro:'Informație observată',en:'Observed information'},identifiers:['Sobs'],summary:{ro:'Eșantionul informațional care a trecut efectiv prin selecție și acces și este disponibil procesării ulterioare.',en:'The information sample that has actually passed selection and access and is available for downstream processing.'},theory:{ro:'CEM tratează eșantionul observat ca diferit atât de pool-ul disponibil, cât și de adevărul lumii. În M1.E1, Sobs rezumă balanța semnată a elementelor observate.',en:'CEM treats the observed sample as distinct from both the available pool and world truth. In M1.E1, Sobs summarizes the signed balance of observed items.'},chapterSlug:'world-information-representation',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:['REF.TOHIDI.2025'],provenance:{ro:'Trebuie să poată fi urmărit înapoi la elementele selectate și condițiile de acces.',en:'It should be traceable back to selected items and access conditions.'},uncertainty:{ro:'Un eșantion observat poate fi sistematic nereprezentativ pentru informația disponibilă.',en:'An observed sample can be systematically unrepresentative of available information.'},limitation:{ro:'Sobs nu este adevărul evenimentului și nici opinia agentului.',en:'Sobs is neither event truth nor the agent’s opinion.'}},
 {id:'exposure',x:27,y:34,group:'representation',label:{ro:'Expunere și repetiție',en:'Exposure and repetition'},identifiers:['Nexp'],summary:{ro:'Istoricul expunerilor la o afirmație alimentează mecanismul de familiaritate.',en:'Exposure history to a claim feeds the familiarity mechanism.'},theory:{ro:'Nexp numără expunerile și rămâne separat de familiaritate. Repetiția poate crește familiaritatea chiar dacă nu adaugă dovezi factuale.',en:'Nexp counts exposures and remains distinct from familiarity. Repetition can increase familiarity even when no factual evidence is added.'},chapterSlug:'repetition-familiarity-truth',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.HASHER.1977','REF.DECHENE.2010'],provenance:{ro:'Evenimentele de expunere trebuie datate și legate de afirmația/sursa relevantă.',en:'Exposure events should be timestamped and linked to the relevant claim/source.'},uncertainty:{ro:'Numărul expunerilor nu indică ce a fost reținut sau crezut.',en:'Exposure count does not indicate what was retained or believed.'},limitation:{ro:'Nexp nu este familiaritate, adevăr sau cantitate de dovadă.',en:'Nexp is not familiarity, truth or amount of evidence.'}},
 {id:'familiarity',x:27,y:54,group:'representation',label:{ro:'Familiaritate',en:'Familiarity'},identifiers:['F'],summary:{ro:'Stare latentă care crește odată cu repetarea și poate contribui la plauzibilitatea percepută.',en:'Latent state that increases with repetition and can contribute to judged plausibility.'},theory:{ro:'Efectul de adevăr iluzoriu arată că familiaritatea poate influența judecata. CEM o modelează separat de dovadă, fiabilitatea sursei și adevăr.',en:'Illusory-truth research shows that familiarity can influence judgment. CEM models it separately from evidence, source reliability and truth.'},chapterSlug:'repetition-familiarity-truth',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.HASHER.1977','REF.DECHENE.2010'],provenance:{ro:'F este derivată în model din istoricul de expunere al rulării de referință.',en:'F is derived in the model from exposure history in the reference run.'},uncertainty:{ro:'Magnitudinea efectului real depinde de sarcină și populație; coeficienții M0 sunt necalibrați populațional.',en:'Real effect magnitude depends on task and population; M0 coefficients are not population-calibrated.'},limitation:{ro:'Familiaritatea nu este adevăr, dovadă sau fiabilitate.',en:'Familiarity is not truth, evidence or reliability.'}},
 {id:'correction',x:27,y:74,group:'representation',label:{ro:'Corecție și accesibilitate',en:'Correction and accessibility'},identifiers:['C'],summary:{ro:'Reprezintă accesibilitatea curentă a contextului corectiv și felul în care aceasta poate scădea după corecție.',en:'Represents current accessibility of corrective context and how it can decline after a correction.'},theory:{ro:'CEM separă existența unei corecții de accesibilitatea ei ulterioară. Scăderea lui C nu înseamnă ștergerea memoriei și o corecție nu garantează schimbarea convingerii.',en:'CEM separates the existence of a correction from its later accessibility. Decline in C does not mean memory erasure, and a correction does not guarantee belief change.'},chapterSlug:'corrections-accessibility-memory',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.WM.ECKER.2022'],provenance:{ro:'Evenimentul corectiv și timpul scurs sunt păstrate ca intrări distincte.',en:'Correction event and elapsed time are retained as distinct inputs.'},uncertainty:{ro:'Forma de decay este o alegere de referință și nu o estimare populațională universală.',en:'The decay form is a reference choice, not a universal population estimate.'},limitation:{ro:'C nu garantează corectarea convingerii și nu măsoară ștergerea memoriei.',en:'C does not guarantee belief correction and does not measure memory erasure.'}},
 {id:'memory-prior',x:46,y:12,group:'representation',label:{ro:'Memorie și informație anterioară',en:'Memory and prior information'},identifiers:['Pprior when justified'],summary:{ro:'Cunoștințele, memoria și regularitățile învățate pot constrânge interpretarea și punctul de pornire al unei actualizări.',en:'Knowledge, memory and learned regularities can constrain interpretation and the starting point of an update.'},theory:{ro:'MOD.14 tratează memoria și informația anterioară ca surse pentru reprezentare, dar permite un Pprior numeric numai când sarcina îi oferă o interpretare probabilistică justificabilă.',en:'MOD.14 treats memory and prior information as inputs to representation, but permits a numeric Pprior only when the task gives it a defensible probabilistic interpretation.'},chapterSlug:'world-model-construction',statuses:['EMPIRICAL','CONCEPTUAL'],evidenceRefs:['REF.WM.ZWAAN_RADVANSKY.1998'],provenance:{ro:'Originea priorului trebuie declarată: date de bază, instrucțiuni, memorie sau altă sursă.',en:'The origin of a prior must be declared: base-rate data, instructions, memory or another source.'},uncertainty:{ro:'O credință anterioară psihologică nu este automat o probabilitate calibrată.',en:'A psychological prior belief is not automatically a calibrated probability.'},limitation:{ro:'CEM nu transformă automat memoria sau schema într-un Pprior numeric.',en:'CEM does not automatically turn memory or schema into a numeric Pprior.'}},
 {id:'source-provenance',x:46,y:34,group:'representation',label:{ro:'Sursă și proveniență',en:'Source and provenance'},identifiers:['T','Prov'],summary:{ro:'Separă originea dovezii de estimarea agentului privind fiabilitatea sursei.',en:'Separates evidence origin from the agent’s estimate of source reliability.'},theory:{ro:'CEM distinge proveniența, fiabilitatea estimată T și calitatea reală a sursei. MOD.14 menține aceste concepte separate de diagnosticitatea statistică a unei dovezi.',en:'CEM distinguishes provenance, estimated reliability T and actual source quality. MOD.14 keeps these separate from statistical diagnosticity of evidence.'},chapterSlug:'sources-feedback-reliability',statuses:['EMPIRICAL','CONCEPTUAL','EXECUTABLE'],evidenceRefs:['REF.WM.JOHNSON.1993','REF.WM.SPERBER.2010'],provenance:{ro:'Identitatea sursei, contextul de achiziție și feedbackul despre sursă trebuie păstrate distinct.',en:'Source identity, acquisition context and feedback about the source should remain distinct.'},uncertainty:{ro:'T este o estimare a agentului și poate fi greșită; proveniența singură nu certifică adevărul.',en:'T is an agent estimate and can be wrong; provenance alone does not certify truth.'},limitation:{ro:'T și Prov nu sunt LR și nu sunt certificate de adevăr.',en:'T and Prov are not LR and are not truth certificates.'}},
 {id:'social-context',x:46,y:56,group:'representation',label:{ro:'Context social',en:'Social context'},identifiers:['source cues','consensus / independence'],summary:{ro:'Interpretarea informației comunicate depinde și de surse, consens aparent, norme și dependența dintre semnale.',en:'Interpretation of communicated information also depends on sources, apparent consensus, norms and dependence between signals.'},theory:{ro:'MOD.14 păstrează contextul social conceptual până când o sarcină oferă o măsurare validată. Zece redistribuiri ale aceleiași surse nu devin zece observații independente.',en:'MOD.14 keeps social context conceptual until a task supplies a validated measure. Ten reposts of the same source do not become ten independent observations.'},chapterSlug:'algorithms-social-feedback',statuses:['EMPIRICAL','CONCEPTUAL'],evidenceRefs:['REF.WM.SPERBER.2010','REF.WM.ECKER.2022'],provenance:{ro:'Independența surselor și lanțul de retransmitere trebuie păstrate atunci când sunt cunoscute.',en:'Source independence and retransmission chains should be preserved when known.'},uncertainty:{ro:'Consensul aparent poate proveni din surse dependente sau selecție algoritmică.',en:'Apparent consensus can arise from dependent sources or algorithmic selection.'},limitation:{ro:'Nu există în CEM un multiplicator generic de conformism.',en:'CEM has no generic conformity multiplier.'}},
 {id:'diagnosticity',x:46,y:78,group:'integration',label:{ro:'Diagnosticitatea dovezii',en:'Evidence diagnosticity'},identifiers:['LR'],summary:{ro:'Raport statistic extern care descrie cât de diagnostică este o observație pentru o propoziție binară.',en:'Externally justified statistical ratio describing how diagnostic an observation is for a binary proposition.'},theory:{ro:'În operatorul normativ MOD.14, LR trebuie furnizat de un model diagnostic sau de măsurare justificabil. Nu este dedus din familiaritate, încrederea în sursă, saliență sau consens.',en:'In the MOD.14 normative operator, LR must come from a defensible diagnostic or measurement model. It is not inferred from familiarity, source trust, salience or consensus.'},chapterSlug:'world-model-construction',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:[],provenance:{ro:'Sursa și ipotezele modelului care furnizează LR trebuie înregistrate.',en:'The source and assumptions of the model supplying LR must be recorded.'},uncertainty:{ro:'Dacă LR nu este justificabil, operatorul eșuează închis și nu calculează posteriorul.',en:'If LR is not defensible, the operator fails closed and computes no posterior.'},limitation:{ro:'LR nu este încredere, familiaritate, cantitate de informație sau scor de consens.',en:'LR is not trust, familiarity, information amount or a consensus score.'}},
 {id:'world-model',x:65,y:18,group:'integration',label:{ro:'Model normativ al realității',en:'Normative world model'},identifiers:['Pwm'],summary:{ro:'Posterior normativ transparent pentru o propoziție, calculat numai dintr-un prior și un LR justificabile.',en:'Transparent normative proposition posterior computed only from a defensible prior and LR.'},theory:{ro:'Pwm este o referință normativă la nivel de propoziție, nu descrierea completă a cogniției umane și nu un oracol al adevărului. El rămâne explicit separat de B.',en:'Pwm is a proposition-level normative reference, not a complete description of human cognition and not a truth oracle. It remains explicitly distinct from B.'},chapterSlug:'world-model-construction',statuses:['EXECUTABLE','CONCEPTUAL','INTERPRETIVE'],evidenceRefs:['REF.WM.ERNST_BANKS.2002','REF.WM.KNILL_POUGET.2004'],provenance:{ro:'Pprior, LR și proveniența fiecărui item de evidență trebuie păstrate împreună cu rezultatul.',en:'Pprior, LR and the provenance of each evidence item should be retained with the result.'},uncertainty:{ro:'Corectitudinea algebrică a operatorului nu demonstrează că oamenii îl urmează într-un domeniu real.',en:'Algebraic correctness of the operator does not show that people follow it in a real domain.'},limitation:{ro:'Pwm nu este B, adevăr, cunoaștere sau opinie populațională.',en:'Pwm is not B, truth, knowledge or population opinion.'}},
 {id:'uncertainty',x:65,y:42,group:'integration',label:{ro:'Incertitudine explicită',en:'Explicit uncertainty'},identifiers:['Uwm'],summary:{ro:'Entropie binară normalizată derivată din Pwm pentru a păstra incertitudinea vizibilă.',en:'Normalized binary entropy derived from Pwm to keep uncertainty explicit.'},theory:{ro:'Uwm este maximă când posteriorul este 0,5 și zero la 0 sau 1. Ea descrie numai incertitudinea stării binare normative, nu necunoașterea modelului sau necunoscutele necunoscute.',en:'Uwm is maximal at posterior 0.5 and zero at 0 or 1. It describes only uncertainty within the binary normative state, not model ignorance or unknown unknowns.'},chapterSlug:'world-model-construction',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:['REF.WM.KNILL_POUGET.2004'],provenance:{ro:'Uwm este derivată determinist din Pwm și trebuie legată de aceleași intrări și ipoteze.',en:'Uwm is deterministically derived from Pwm and should remain linked to the same inputs and assumptions.'},uncertainty:{ro:'Nu include incertitudinea privind specificarea modelului, dependența dovezilor sau ontologii conflictuale.',en:'It does not include uncertainty about model specification, evidence dependence or conflicting ontologies.'},limitation:{ro:'Uwm nu este încredere metacognitivă și nu certifică acuratețea.',en:'Uwm is not metacognitive confidence and does not certify accuracy.'}},
 {id:'appraisal',x:65,y:66,group:'integration',label:{ro:'Evaluarea subiectului',en:'Issue appraisal'},identifiers:['Aissue'],summary:{ro:'Stare mărginită care rezumă evaluarea curentă a unui eveniment după eșantionul observat.',en:'Bounded state summarizing current appraisal of an event after the observed sample.'},theory:{ro:'Aissue aparține extensiilor M1 și rămâne distinctă de B, care reprezintă propensiunea de a judeca adevărul unei afirmații.',en:'Aissue belongs to the M1 extensions and remains distinct from B, the propensity to judge a claim as true.'},chapterSlug:'editorial-selection-observed-world',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:['REF.TOHIDI.2025'],provenance:{ro:'Trebuie legată de Sobs și de condiția editorială care a produs eșantionul observat.',en:'It should remain linked to Sobs and the editorial condition that produced the observed sample.'},uncertainty:{ro:'Nu este o măsură populațională calibrată și nu poate fi interpretată în afara sarcinii de referință.',en:'It is not a calibrated population measure and cannot be interpreted outside the reference task.'},limitation:{ro:'Aissue nu este B, adevăr, ideologie sau diagnostic afectiv.',en:'Aissue is not B, truth, ideology or an affective diagnosis.'}},
 {id:'belief',x:84,y:18,group:'integration',label:{ro:'Convingere despre afirmație',en:'Claim belief'},identifiers:['B'],summary:{ro:'Propensiunea latentă descriptivă de a judeca o afirmație drept adevărată la un moment dat.',en:'Descriptive latent propensity to judge a claim as true at a given time.'},theory:{ro:'B integrează stările descriptive ale nucleului M0 și rămâne separat de posteriorul normativ Pwm. O discrepanță B–Pwm poate fi informativă și nu trebuie eliminată prin definiție.',en:'B integrates descriptive M0 states and remains separate from normative posterior Pwm. A B–Pwm discrepancy can be informative and should not be eliminated by definition.'},chapterSlug:'belief-accuracy-action',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:['REF.HASHER.1977','REF.WM.ECKER.2022'],provenance:{ro:'În rulările de referință, B trebuie urmărit împreună cu stările și evenimentele care îl preced.',en:'In reference runs, B should be traced with the states and events that precede it.'},uncertainty:{ro:'B este latent și dependent de forma modelului; nu este o probabilitate populațională calibrată.',en:'B is latent and model-form dependent; it is not a calibrated population probability.'},limitation:{ro:'B nu este cunoaștere, adevăr, ideologie sau angajament identitar.',en:'B is not knowledge, truth, ideology or identity commitment.'}},
 {id:'accuracy-weighting',x:84,y:42,group:'judgment',label:{ro:'Ponderea acurateții',en:'Accuracy weighting'},identifiers:['W'],summary:{ro:'Pondere contextuală acordată acurateții în politica de distribuire.',en:'Contextual weight given to accuracy in the sharing policy.'},theory:{ro:'Indiciile de acuratețe pot modifica decizia de distribuire fără să modifice direct B. CEM folosește W pentru această separare între convingere și politică de acțiune.',en:'Accuracy cues can change sharing decisions without directly changing B. CEM uses W to separate belief from the action policy.'},chapterSlug:'belief-accuracy-action',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.PENNYCOOK.2021'],provenance:{ro:'Momentul și condiția indiciului de acuratețe trebuie păstrate în rulare.',en:'Timing and condition of the accuracy cue should be retained in the run.'},uncertainty:{ro:'W nu măsoară raționalitatea generală și coeficienții de referință nu sunt estimări universale.',en:'W does not measure general rationality and reference coefficients are not universal estimates.'},limitation:{ro:'W nu este activarea Sistemului 2 și nu este acuratețea reală a agentului.',en:'W is not System 2 activation and is not the agent’s actual accuracy.'}},
 {id:'judgment',x:84,y:66,group:'judgment',label:{ro:'Judecată / decizie',en:'Judgment / decision'},identifiers:['DecisionEvent'],summary:{ro:'Momentul în care stările curente sunt transformate într-o evaluare sau într-o politică de răspuns.',en:'Point at which current states are translated into an evaluation or response policy.'},theory:{ro:'CEM separă mecanismele care formează stările interne de etapa în care acestea sunt folosite pentru judecată și decizie.',en:'CEM separates mechanisms that form internal states from the stage where those states are used for judgment and decision.'},chapterSlug:'belief-accuracy-action',statuses:['EXECUTABLE','CONCEPTUAL'],evidenceRefs:['REF.PENNYCOOK.2021'],provenance:{ro:'Evenimentul de decizie trebuie legat de starea modelului la același pas.',en:'The decision event should be linked to model state at the same step.'},uncertainty:{ro:'O decizie observată nu dezvăluie fără ambiguitate toate stările interne care au produs-o.',en:'An observed decision does not uniquely reveal all internal states that produced it.'},limitation:{ro:'Judecata și acțiunea nu sunt sinonime cu adevărul sau cu o trăsătură stabilă a persoanei.',en:'Judgment and action are not synonyms for truth or a stable personal trait.'}},
 {id:'action',x:84,y:88,group:'judgment',label:{ro:'Distribuire și acțiune',en:'Sharing and action'},identifiers:['Share','Pengage','EngageIntent'],summary:{ro:'Rezultatele observabile sau simulate ale politicilor de răspuns.',en:'Observable or simulated outcomes of response policies.'},theory:{ro:'CEM diferențiază Share din M0, engagement-ul declarat M1.E2 și accesul M1.E3. O acțiune nu este automat echivalentă cu o convingere sau cu aprobarea conținutului.',en:'CEM distinguishes M0 Share, M1.E2 declared engagement and M1.E3 access. An action is not automatically equivalent to belief or endorsement.'},chapterSlug:'belief-accuracy-action',statuses:['EMPIRICAL','EXECUTABLE'],evidenceRefs:['REF.PENNYCOOK.2021','REF.ROBERTSON.2023.NEGATIVITY'],provenance:{ro:'Tipul exact de outcome și condiția experimentală trebuie păstrate; outcome-urile nu sunt interschimbabile.',en:'The exact outcome type and experimental condition must be retained; outcomes are not interchangeable.'},uncertainty:{ro:'Probabilitățile modelului de referință nu sunt rate populaționale calibrate.',en:'Reference-model probabilities are not calibrated population rates.'},limitation:{ro:'Share, EngageIntent și Access nu sunt echivalente între ele și nu certifică endorsement.',en:'Share, EngageIntent and Access are not interchangeable and do not certify endorsement.'}},
 {id:'reassessment',x:65,y:88,group:'integration',label:{ro:'Contradicție și reevaluare',en:'Contradiction and reassessment'},identifiers:['revision loop'],summary:{ro:'Contra-dovezile, corecțiile sau reevaluarea sursei pot declanșa revizuirea reprezentării.',en:'Counterevidence, corrections or source reappraisal can trigger revision of the representation.'},theory:{ro:'MOD.14 cere ca reprezentarea să rămână revizuibilă. Reevaluarea este o buclă conceptuală și empirică; forma descriptivă exactă rămâne dependentă de sarcină.',en:'MOD.14 requires the representation to remain revisable. Reassessment is a conceptual and empirical loop; its exact descriptive form remains task-dependent.'},chapterSlug:'world-model-construction',statuses:['EMPIRICAL','CONCEPTUAL'],evidenceRefs:['REF.WM.ECKER.2022'],provenance:{ro:'Motivul reevaluării trebuie legat de noua dovadă, corecție sau schimbare de proveniență.',en:'The trigger for reassessment should be linked to new evidence, correction or provenance change.'},uncertainty:{ro:'CEM nu impune o singură ecuație universală pentru reevaluarea umană.',en:'CEM imposes no single universal equation for human reassessment.'},limitation:{ro:'Bucla nu reactivează M1.E4, Pencode sau calibrarea populațională.',en:'The loop does not reactivate M1.E4, Pencode or population calibration.'}}
];

export const cemProductEdges:CemProductEdge[]=[
 {id:'available-selection',source:'available-information',target:'selection',label:{ro:'selecție din pool',en:'select from pool'},level:'CONCEPTUAL'},
 {id:'selection-presentation',source:'selection',target:'presentation',label:{ro:'elemente selectate sunt prezentate',en:'selected items are presented'},level:'CONCEPTUAL'},
 {id:'presentation-access',source:'presentation',target:'access-gate',label:{ro:'forma condiționează accesul',en:'presentation conditions access'},level:'CONCEPTUAL'},
 {id:'access-observed',source:'access-gate',target:'observed-information',label:{ro:'ce trece poarta devine observabil',en:'what passes the gate becomes observable'},level:'CONCEPTUAL'},
 {id:'observed-exposure',source:'observed-information',target:'exposure',label:{ro:'evenimente de expunere',en:'exposure events'},level:'EXECUTABLE'},
 {id:'exposure-familiarity',source:'exposure',target:'familiarity',label:{ro:'repetiția crește familiaritatea',en:'repetition increases familiarity'},level:'EXECUTABLE'},
 {id:'familiarity-belief',source:'familiarity',target:'belief',label:{ro:'contribuie la plauzibilitate',en:'contributes to plausibility'},level:'EXECUTABLE'},
 {id:'correction-belief',source:'correction',target:'belief',label:{ro:'context corectiv accesibil',en:'accessible corrective context'},level:'EXECUTABLE'},
 {id:'correction-reassessment',source:'correction',target:'reassessment',label:{ro:'poate declanșa reevaluarea',en:'can trigger reassessment'},level:'CONCEPTUAL'},
 {id:'observed-appraisal',source:'observed-information',target:'appraisal',label:{ro:'eșantionul formează evaluarea',en:'sample informs appraisal'},level:'EXECUTABLE'},
 {id:'observed-world',source:'observed-information',target:'world-model',label:{ro:'observația intră în reprezentare',en:'observation enters representation'},level:'CONCEPTUAL'},
 {id:'memory-world',source:'memory-prior',target:'world-model',label:{ro:'prior justificabil',en:'defensible prior'},level:'CONCEPTUAL'},
 {id:'source-diagnosticity',source:'source-provenance',target:'diagnosticity',label:{ro:'bridge de măsurare necesar',en:'measurement bridge required'},level:'CONCEPTUAL'},
 {id:'social-world',source:'social-context',target:'world-model',label:{ro:'interpretare contextuală',en:'contextual interpretation'},level:'CONCEPTUAL'},
 {id:'diagnosticity-world',source:'diagnosticity',target:'world-model',label:{ro:'LR actualizează priorul',en:'LR updates prior'},level:'EXECUTABLE'},
 {id:'world-uncertainty',source:'world-model',target:'uncertainty',label:{ro:'entropie derivată',en:'derived entropy'},level:'EXECUTABLE'},
 {id:'world-reassessment',source:'world-model',target:'reassessment',label:{ro:'posteriorul rămâne revizuibil',en:'posterior remains revisable'},level:'CONCEPTUAL'},
 {id:'reassessment-memory',source:'reassessment',target:'memory-prior',label:{ro:'actualizează contextul pentru ciclul următor',en:'updates context for the next cycle'},level:'CONCEPTUAL'},
 {id:'belief-judgment',source:'belief',target:'judgment',label:{ro:'stare descriptivă folosită în judecată',en:'descriptive state used in judgment'},level:'CONCEPTUAL'},
 {id:'appraisal-judgment',source:'appraisal',target:'judgment',label:{ro:'evaluarea informează răspunsul',en:'appraisal informs response'},level:'CONCEPTUAL'},
 {id:'belief-action',source:'belief',target:'action',label:{ro:'intrare în politica de acțiune',en:'input to action policy'},level:'EXECUTABLE'},
 {id:'accuracy-action',source:'accuracy-weighting',target:'action',label:{ro:'pondere contextuală a acurateții',en:'contextual accuracy weight'},level:'EXECUTABLE'},
 {id:'judgment-action',source:'judgment',target:'action',label:{ro:'decizia produce outcome',en:'decision produces outcome'},level:'CONCEPTUAL'}
];

export const cemDiagnostics:CemDiagnostic[]=[
 {id:'diag-familiarity',focus:'familiarity',title:{ro:'Familiaritatea poate depăși dovezile',en:'Familiarity can outrun evidence'},why:{ro:'Repetiția poate crește plauzibilitatea percepută fără să adauge informație diagnostică nouă.',en:'Repetition can increase judged plausibility without adding new diagnostic information.'},mechanisms:['exposure','familiarity','belief'],evidence:{ro:'Efect empiric bine documentat; traseu M0 executabil.',en:'Well-documented empirical effect; executable M0 pathway.'},uncertainty:{ro:'Magnitudinea și coeficienții nu sunt calibrați populațional în CEM.',en:'Magnitude and coefficients are not population-calibrated in CEM.'},statuses:['EMPIRICAL','EXECUTABLE']},
 {id:'diag-correction',focus:'correction',title:{ro:'Corecția poate pierde accesibilitate',en:'Corrective context can lose accessibility'},why:{ro:'Existența unei corecții nu garantează că ea rămâne disponibilă atunci când afirmația este judecată ulterior.',en:'The existence of a correction does not guarantee that it remains available when the claim is judged later.'},mechanisms:['correction','reassessment','belief'],evidence:{ro:'Fenomen empiric și mecanism de referință executabil.',en:'Empirical phenomenon with an executable reference mechanism.'},uncertainty:{ro:'Forma exactă a decay-ului este o alegere de model, nu o lege universală.',en:'Exact decay form is a model choice, not a universal law.'},statuses:['EMPIRICAL','EXECUTABLE']},
 {id:'diag-selection',focus:'observed-information',title:{ro:'Eșantionul observat poate fi sistematic distorsionat',en:'The observed sample can be systematically distorted'},why:{ro:'Selecția, framing-ul și accesul determină ce subset din informația disponibilă ajunge la evaluare.',en:'Selection, framing and access determine which subset of available information reaches appraisal.'},mechanisms:['selection','presentation','access-gate','observed-information','appraisal'],evidence:{ro:'M1.E1–E3 combină dovezi empirice cu mecanisme de referință executabile.',en:'M1.E1–E3 combine empirical evidence with executable reference mechanisms.'},uncertainty:{ro:'Efectele sunt task-specific și nu reprezintă estimări populaționale universale.',en:'Effects are task-specific and are not universal population estimates.'},statuses:['EMPIRICAL','EXECUTABLE']},
 {id:'diag-source',focus:'source-provenance',title:{ro:'Încrederea în sursă nu este diagnosticitatea dovezii',en:'Source trust is not evidence diagnosticity'},why:{ro:'T, proveniența și LR răspund la întrebări diferite; confundarea lor poate produce certitudine nejustificată.',en:'T, provenance and LR answer different questions; conflating them can create unjustified certainty.'},mechanisms:['source-provenance','diagnosticity','world-model'],evidence:{ro:'Separare susținută de literatura despre source monitoring și formalizată conceptual în MOD.14.',en:'Separation supported by source-monitoring literature and formalized conceptually in MOD.14.'},uncertainty:{ro:'Nu există bridge universal de la reputația sursei la LR.',en:'There is no universal bridge from source reputation to LR.'},statuses:['EMPIRICAL','CONCEPTUAL']},
 {id:'diag-divergence',focus:'world-model',title:{ro:'B și Pwm pot diverge legitim',en:'B and Pwm can legitimately diverge'},why:{ro:'B descrie o stare latentă a agentului; Pwm este o referință normativă bazată pe intrări probabilistice declarate.',en:'B describes a latent agent state; Pwm is a normative reference based on declared probabilistic inputs.'},mechanisms:['belief','world-model','uncertainty'],evidence:{ro:'Distincție de arhitectură; operatorul Pwm/Uwm este executabil și testat algebric.',en:'Architectural distinction; the Pwm/Uwm operator is executable and algebraically tested.'},uncertainty:{ro:'Corectitudinea software nu validează descriptiv comportamentul uman.',en:'Software correctness does not descriptively validate human behavior.'},statuses:['EXECUTABLE','CONCEPTUAL']},
 {id:'diag-action',focus:'accuracy-weighting',title:{ro:'Acțiunea se poate schimba fără schimbarea convingerii',en:'Action can change without belief changing'},why:{ro:'Un indiciu de acuratețe poate modifica ponderea W în politica de distribuire fără să modifice direct B.',en:'An accuracy cue can change W in the sharing policy without directly changing B.'},mechanisms:['belief','accuracy-weighting','judgment','action'],evidence:{ro:'Susținut empiric de accuracy prompts și reprezentat în mecanismul M0 de decizie.',en:'Supported empirically by accuracy prompts and represented in the M0 decision mechanism.'},uncertainty:{ro:'W nu este o măsură generală a raționalității sau a controlului cognitiv.',en:'W is not a general measure of rationality or cognitive control.'},statuses:['EMPIRICAL','EXECUTABLE']}
];

export const nodeById=(id:string)=>cemProductNodes.find(node=>node.id===id);
