import release from '../public/model/version.json';
import {scenarioName} from './labels';
type Lang='ro'|'en';
type Frame={time:number;belief:number;share_probability:number;correction:number;familiarity:number;reliability:number;accuracy_weight:number};
type Run={id:string;seed:number;prior:number;parameters:Record<string,number>;frames:Frame[]};
const state={selected:'correction',step:5};
export function mountComparison(host:HTMLElement,runs:Run[],lang:Lang,onInspect:(id:string,step:number)=>void){
 const t=(ro:string,en:string)=>lang==='ro'?ro:en;
 const n=(v:number)=>v.toLocaleString(lang==='ro'?'ro-RO':'en-GB',{minimumFractionDigits:3,maximumFractionDigits:3});
 const signed=(v:number)=>(v>0?'+':v<0?'−':'')+n(Math.abs(v));
 const names:Record<string,string>=Object.fromEntries(runs.map(r=>[r.id,scenarioName(r.id,lang)]));
 const descriptions:Record<string,string>={
 repetition:t('Ambele curbe reprezintă aceeași rulare. Diferențele trebuie să fie zero la fiecare pas.','Both curves represent the same run. Differences must be zero at every step.'),
 correction:t('Față de repetiția simplă, la pasul 5 este introdusă o corecție negativă. Ulterior, accesibilitatea ei scade. Programul expunerilor și celelalte intrări rămân aceleași.','Relative to repetition only, a negative correction is introduced at step 5. Its accessibility subsequently decays. Exposure timing and other inputs remain the same.'),
 source:t('Această comparație schimbă două intrări: introduce feedback negativ despre sursă la pașii 2, 4, 6 și 8 și folosește evidență +0,6 în loc de 0. Nu izolează efectul feedbackului singur; rezultatul depinde de interacțiunea lui cu semnalul.','This comparison changes two inputs: negative source feedback at steps 2, 4, 6 and 8, and evidence +0.6 instead of 0. It does not isolate feedback alone; the result depends on its interaction with the signal.'),
 accuracy:t('De la pasul 5 este activat indiciul de acuratețe. El schimbă W și probabilitatea de distribuire, fără să schimbe convingerea B.','An accuracy cue is active from step 5. It changes W and sharing probability without changing belief B.')};
 const baseline=runs.find(r=>r.id==='repetition')!;
 const current=()=>runs.find(r=>r.id===state.selected)!;
 const difference=(key:keyof Frame,i:number)=>current().frames[i][key]-baseline.frames[i][key];
 const meanDifference=(key:keyof Frame)=>baseline.frames.reduce((s,_,i)=>s+difference(key,i),0)/baseline.frames.length;
 host.innerHTML=`<div class="section-heading"><div><h2>${t('Compară traiectoriile mecanismelor','Compare mechanism trajectories')}</h2><p>${t('Aceeași stare inițială și același program de expuneri, cu diferențele de intrare explicate pentru fiecare scenariu. Rezultate demonstrative, nu efecte măsurate în populație.','The same initial state and exposure schedule, with input differences explained for each scenario. Demonstration results, not measured population effects.')}</p></div></div><section class="panel comparison-controls"><div><label for="comparisonScenario">${t('Rularea comparată','Comparison run')}</label><select id="comparisonScenario">${runs.map(r=>`<option value="${r.id}" ${state.selected===r.id?'selected':''}>${names[r.id]}</option>`).join('')}</select></div><div><strong>${t('Reper fix','Fixed reference')}</strong><p>${names.repetition} · ${t('convingere inițială','prior belief')} ${n(baseline.prior)}</p></div><p class="note">${t('Ambele rulări au patru expuneri, la pașii 1–4, și aceiași coeficienți. Comparăm probabilitățile, nu acțiunile aleatoare.','Both runs have four exposures at steps 1–4 and the same coefficients. We compare probabilities, not random actions.')}</p></section><section class="panel comparison-context"><h3>${t('Ce diferă între rulări?','What differs between runs?')}</h3><p id="comparisonContext"></p></section><div class="comparison-charts" id="comparisonCharts"></div><section class="panel"><div class="comparison-transport"><button id="comparePrevious">${t('Pasul anterior','Previous step')}</button><label for="compareTimeline">${t('Pasul inspectat','Inspected step')} <output id="compareStep"></output></label><input id="compareTimeline" type="range" min="0" max="12" step="1" value="${state.step}"><button id="compareNext">${t('Pasul următor','Next step')}</button></div><div id="comparisonValues" aria-live="polite"></div><button id="inspectCompared">${t('Explică în detaliu pasul selectat','Explain the selected step in detail')}</button></section><section class="panel comparison-summary" id="comparisonSummary"></section><details class="panel comparison-table"><summary>${t('Valorile și diferențele tuturor pașilor','Values and differences at every step')}</summary><div class="table-scroll"><table><caption>${t('Diferență = rularea comparată − repetiție simplă. Valori în unități 0–1, nu procente.','Difference = comparison run − repetition only. Values in 0–1 units, not percentages.')}</caption><thead><tr><th>${t('Pas','Step')}</th><th>B · ${t('reper','reference')}</th><th>B · ${t('comparată','comparison')}</th><th>ΔB</th><th>P · ${t('reper','reference')}</th><th>P · ${t('comparată','comparison')}</th><th>ΔP</th></tr></thead><tbody id="comparisonRows"></tbody></table></div></details><button id="downloadComparison">${t('Descarcă comparația JSON','Download comparison JSON')}</button>`;
 function chart(key:'belief'|'share_probability',title:string){
  const x=(time:number)=>48+time*40,y=(v:number)=>226-v*196;
  const line=(r:Run,color:string,dash:string)=>`<polyline fill="none" stroke="${color}" stroke-width="3" stroke-dasharray="${dash}" points="${r.frames.map(f=>`${x(f.time)},${y(f[key])}`).join(' ')}"/>`;
  return `<section class="panel"><h3>${title}</h3><div class="comparison-legend"><span class="comp-reference">${names.repetition}</span><span class="comp-selected">${names[state.selected]}</span></div><div class="comparison-plot"><svg viewBox="0 0 570 270" role="img" aria-label="${title}. ${t('Valorile exacte sunt afișate sub grafice și în tabel.','Exact values are shown below the charts and in the table.')}">${[0,.25,.5,.75,1].map(v=>`<line x1="48" x2="528" y1="${y(v)}" y2="${y(v)}" stroke="var(--border)"/><text x="38" y="${y(v)+5}" text-anchor="end">${v.toLocaleString(lang)}</text>`).join('')}${baseline.frames.map(f=>`<text x="${x(f.time)}" y="254" text-anchor="middle">${f.time}</text>`).join('')}${line(current(),'var(--accent)','none')}${line(baseline,'var(--muted)','7 5')}<line x1="${x(state.step)}" x2="${x(state.step)}" y1="25" y2="226" stroke="var(--text)" stroke-dasharray="2 4"/><circle cx="${x(state.step)}" cy="${y(current().frames[state.step][key])}" r="5" fill="var(--accent)"/></svg></div><p class="note">${t('Axa orizontală: pași abstracți 0–12. Axa verticală: 0–1, aceeași scară în ambele grafice.','Horizontal axis: abstract steps 0–12. Vertical axis: 0–1, the same scale in both charts.')}</p></section>`;
 }
 function draw(){
  const run=current(),a=baseline.frames[state.step],b=run.frames[state.step];
  host.querySelector('#comparisonContext')!.textContent=descriptions[state.selected];
  host.querySelector('#comparisonCharts')!.innerHTML=chart('belief',t('Convingere B','Belief B'))+chart('share_probability',t('Probabilitatea de distribuire P','Sharing probability P'));
  host.querySelector('#compareStep')!.textContent=String(state.step);
  host.querySelector<HTMLInputElement>('#compareTimeline')!.value=String(state.step);
  host.querySelector<HTMLButtonElement>('#comparePrevious')!.disabled=state.step===0;host.querySelector<HTMLButtonElement>('#compareNext')!.disabled=state.step===12;
  host.querySelector('#comparisonValues')!.innerHTML=`<div class="comparison-metrics"><div><h3>${t('Convingere la acest pas','Belief at this step')}</h3><p>${t('Reper','Reference')}: ${n(a.belief)} → ${t('comparată','comparison')}: ${n(b.belief)}</p><strong id="deltaBelief">ΔB = ${signed(difference('belief',state.step))}</strong></div><div><h3>${t('Distribuire la acest pas','Sharing at this step')}</h3><p>${t('Reper','Reference')}: ${n(a.share_probability)} → ${t('comparată','comparison')}: ${n(b.share_probability)}</p><strong id="deltaSharing">ΔP = ${signed(difference('share_probability',state.step))}</strong></div></div><p class="note">${t('Semnul minus indică o valoare mai mică decât reperul. Nu înseamnă automat un rezultat mai bun: aceasta depinde de adevărul afirmației și de obiectiv.','A minus sign means a lower value than the reference. This is not automatically better: it depends on claim truth and the objective.')}</p>`;
  const first=baseline.frames.findIndex((_,i)=>Math.abs(difference('belief',i))>1e-12||Math.abs(difference('share_probability',i))>1e-12);
  host.querySelector('#comparisonSummary')!.innerHTML=`<h3>${t('Diferența pe întregul interval','Difference over the full interval')}</h3><p>${t('Prima diferență numerică în B sau P','First numerical difference in B or P')}: <strong>${first<0?t('niciuna','none'):t('pasul ','step ')+first}</strong>.</p><p>${t('Diferența medie pe cei 13 pași','Mean difference across 13 steps')}: ΔB = <strong>${signed(meanDifference('belief'))}</strong>; ΔP = <strong>${signed(meanDifference('share_probability'))}</strong>.</p><p>${t('Media include și pașii anteriori intervenției. Nu reprezintă numărul de persoane influențate sau impactul unei politici. Pentru prioritizare, laboratorul evaluează separat afirmații false și adevărate, combinații și efort.','The mean includes pre-intervention steps. It is not a count of affected people or a policy impact estimate. For prioritization, the lab separately evaluates false and true claims, bundles and effort.')}</p>`;
  host.querySelector('#comparisonRows')!.innerHTML=baseline.frames.map((a,i)=>{const b=run.frames[i];return `<tr><th scope="row">${a.time}</th><td>${n(a.belief)}</td><td>${n(b.belief)}</td><td>${signed(b.belief-a.belief)}</td><td>${n(a.share_probability)}</td><td>${n(b.share_probability)}</td><td>${signed(b.share_probability-a.share_probability)}</td></tr>`;}).join('');
 }
 host.querySelector<HTMLSelectElement>('#comparisonScenario')!.onchange=e=>{state.selected=(e.target as HTMLSelectElement).value;draw();};
 host.querySelector<HTMLInputElement>('#compareTimeline')!.oninput=e=>{state.step=Number((e.target as HTMLInputElement).value);draw();};
 host.querySelector<HTMLButtonElement>('#comparePrevious')!.onclick=()=>{state.step=Math.max(0,state.step-1);draw();};host.querySelector<HTMLButtonElement>('#compareNext')!.onclick=()=>{state.step=Math.min(12,state.step+1);draw();};
 host.querySelector<HTMLButtonElement>('#inspectCompared')!.onclick=()=>onInspect(state.selected,state.step);
 host.querySelector<HTMLButtonElement>('#downloadComparison')!.onclick=()=>{const payload={model_version:release.version,scope:'Illustrative scenario differences, not empirical intervention effects',reference:baseline,comparison:current(),input_difference:descriptions[state.selected],inspected_step:state.step,mean_delta_belief:meanDifference('belief'),mean_delta_sharing:meanDifference('share_probability'),differences:baseline.frames.map((f,i)=>({time:f.time,belief:difference('belief',i),share_probability:difference('share_probability',i)}))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cem-scenario-comparison.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};draw();
}
