/** Computational dependencies, separate from the empirical evidence registry. */
export type Dependency={id:string;source:string;target:string;ro:string;en:string;formula:string;file:string;registered?:string};
export const extraNodes=[
 {id:'P',ro:'P(distribuire)',en:'P(share)',kind:'output'},
 {id:'Prior',ro:'Convingere inițială',en:'Prior belief',kind:'input'},
 {id:'Evidence',ro:'Semnal de evidență',en:'Evidence signal',kind:'input'},
 {id:'Direction',ro:'Direcția corecției',en:'Correction direction',kind:'input'},
 {id:'Cue',ro:'Indiciu de acuratețe',en:'Accuracy cue',kind:'input'},
 {id:'Baseline',ro:'Acuratețe de bază',en:'Baseline accuracy',kind:'input'},
 {id:'Reward',ro:'Recompensă și bias',en:'Reward and bias',kind:'input'},
 {id:'Feedback',ro:'Feedback despre sursă',en:'Source feedback',kind:'input'},
 {id:'Correction',ro:'Eveniment corectiv',en:'Corrective event',kind:'input'},
 {id:'Time',ro:'Timp scurs',en:'Elapsed time',kind:'input'},
 {id:'Random',ro:'Extragere aleatoare',en:'Random draw',kind:'input'}
];
export const dependencies:Dependency[]=[
 {id:'exposure-f',source:'Nexp',target:'F',ro:'Expunerile actualizează familiaritatea cu incremente descrescătoare. Nexp este numărătoarea conceptuală a evenimentelor; Simulator procesează evenimentele, fără să utilizeze un contor Nexp în ecuație.',en:'Exposures update familiarity with decreasing increments. Nexp is the conceptual event count; Simulator processes events without using an Nexp counter in the equation.',formula:'F′ = F + αf(1 − F)',file:'updates.py',registered:'LINK.EXPOSURE.FAMILIARITY'},
 {id:'f-b',source:'F',target:'B',ro:'Familiaritatea contribuie la scorul latent al convingerii. Cu beta_f pozitiv, familiaritatea mai mare crește B dacă celelalte intrări rămân fixe.',en:'Familiarity contributes to latent belief. With positive beta_f, greater familiarity raises B with other inputs fixed.',formula:'zB += βf × F',file:'model.py',registered:'LINK.FAMILIARITY.BELIEF'},
 {id:'c-b',source:'C',target:'B',ro:'Accesibilitatea multiplică direcția corecției. Efectul poate fi negativ, nul sau pozitiv. Familiaritatea rămâne o contribuție separată.',en:'Accessibility multiplies correction direction. The effect can be negative, zero or positive. Familiarity remains a separate contribution.',formula:'zB += βcorrection × C × direction',file:'model.py'},
 {id:'t-b',source:'T',target:'B',ro:'T ponderează semnalul de evidență. La T = 0,5 contribuția este nulă; sub 0,5 semnul evidenței este inversat. Aceasta este o alegere a modelului, nu o regulă psihologică stabilită.',en:'T weights evidence. At T = 0.5 its contribution is zero; below 0.5 the evidence sign is reversed. This is a model choice, not an established psychological rule.',formula:'zB += βsource × evidence × (2T − 1)',file:'model.py'},
 {id:'b-p',source:'B',target:'P',ro:'Convingerea intră în decizie printr-un termen ponderat cu W. Efectul depinde de W; judecata și acțiunea nu sunt aceeași mărime.',en:'Belief enters the decision through a W-weighted term. Its effect depends on W; judgment and action are not the same quantity.',formula:'u += W × (2B − 1)',file:'model.py'},
 {id:'w-p',source:'W',target:'P',ro:'W schimbă simultan ponderea convingerii și a recompensei. Creșterea sa nu reduce universal distribuirea. Relația W → Share din registru este descompusă aici prin probabilitatea intermediară P.',en:'W changes both belief and reward weighting. Increasing W does not universally reduce sharing. The registered W → Share relation is decomposed here through intermediate probability P.',formula:'u = bias + W(2B − 1) + βreward(1 − W)reward',file:'model.py',registered:'LINK.ACCURACY.ACTION'},
 {id:'p-share',source:'P',target:'Share',ro:'O extragere uniformă este comparată cu P. Acțiunea poate varia chiar dacă P este identică. Nu există în M0 o buclă automată Share → expuneri viitoare.',en:'A uniform draw is compared with P. Actions can differ at identical P. M0 has no automatic Share → future exposure feedback loop.',formula:'Share = [random() < P]; P = logistic(u)',file:'simulation.py'},
 {id:'prior-b',source:'Prior',target:'B',ro:'Convingerea inițială intră prin logit. În M0, B calculat la pasul anterior nu înlocuiește automat această valoare inițială.',en:'Prior belief enters through its logit. In M0, previously calculated B does not automatically replace the prior.',formula:'zB += logit(prior)',file:'model.py'},
 {id:'evidence-b',source:'Evidence',target:'B',ro:'Semnalul este o intrare a evenimentului de decizie, în intervalul −1…1. Adevărul din lumea simulată nu este transmis direct funcției de convingere.',en:'The signal is an input of the decision event, ranging from −1 to 1. Simulated truth is not passed directly into belief computation.',formula:'zB += βsource × evidence × (2T − 1)',file:'model.py'},
 {id:'direction-b',source:'Direction',target:'B',ro:'Ultimul eveniment corectiv fixează direcția în intervalul −1…1. Fără un astfel de eveniment, direcția implicită este zero.',en:'The latest corrective event sets direction in −1…1. Without such an event the default direction is zero.',formula:'zB += βcorrection × C × direction',file:'simulation.py'},
 {id:'cue-w',source:'Cue',target:'W',ro:'Indiciul adaugă un deplasament logistic față de nivelul de bază. Nu modifică direct B.',en:'The cue adds a logistic shift from baseline. It does not directly modify B.',formula:'W = logistic(logit(baseline) + βcue × cue)',file:'model.py'},
 {id:'baseline-w',source:'Baseline',target:'W',ro:'Nivelul de bază este o proprietate a agentului, distinctă de indiciul contextual. Nu reprezintă o măsură generală a raționalității.',en:'Baseline is an agent property, distinct from the contextual cue. It is not a general measure of rationality.',formula:'W = logistic(logit(baseline) + shift)',file:'model.py'},
 {id:'reward-p',source:'Reward',target:'P',ro:'Recompensa contextuală este ponderată cu 1 − W. Biasul de distribuire este un termen separat, constant pentru agentul respectiv.',en:'Contextual reward is weighted by 1 − W. Sharing bias is a separate term, constant for the agent.',formula:'u += bias + βreward × (1 − W) × reward',file:'model.py'},
 {id:'feedback-t',source:'Feedback',target:'T',ro:'O confirmare apropie T de 1; o infirmare îl apropie de 0. Viteza ajustării este alpha_t.',en:'Confirmation moves T towards 1; disconfirmation moves it towards 0. Adjustment speed is alpha_t.',formula:'T′ = T + αt(outcome − T)',file:'updates.py'},
 {id:'correction-c',source:'Correction',target:'C',ro:'Evenimentul crește accesibilitatea după aplicarea diminuării de la ultimul moment relevant. Direcția este memorată separat.',en:'The event increases accessibility after decay since the last relevant time. Direction is stored separately.',formula:'C′ = C + αc(1 − C)',file:'updates.py'},
 {id:'time-c',source:'Time',target:'C',ro:'Accesibilitatea scade exponențial cu timpul scurs. În M0, familiaritatea și estimarea sursei nu au o diminuare temporală similară.',en:'Accessibility decays exponentially with elapsed time. M0 has no equivalent time decay for familiarity or source estimates.',formula:'C′ = C × exp(−λc Δt)',file:'updates.py'},
 {id:'random-share',source:'Random',target:'Share',ro:'Seed-ul controlează reproductibilitatea extragerilor. Aleatorul afectează acțiunea Share, nu convingerea B sau probabilitatea P.',en:'The seed controls reproducibility of draws. Randomness affects Share, not belief B or probability P.',formula:'r ∼ Uniform(0,1); Share = [r < P]',file:'simulation.py'}
];
