import type {Explanation} from './explanation';
type Frame={time:number;belief:number;share_probability:number;share:boolean;familiarity:number;correction:number;reliability:number;accuracy_weight:number};
/** Read-only interpretation of the canonical exported decomposition. No simulation here. */
export function graphReading(node:string,frame:Frame,previous:Frame|undefined,e:Explanation,lang:'ro'|'en'){
 const t=(ro:string,en:string)=>lang==='ro'?ro:en;
 const n=(v:number)=>v.toLocaleString(lang==='ro'?'ro-RO':'en-GB',{minimumFractionDigits:3,maximumFractionDigits:3});
 const sign=(v:number)=>(v>0?'+':v<0?'−':'')+n(Math.abs(v));
 const readings:Record<string,{title:string;body:string;value?:number;before?:number;formula?:string;term?:number;limit:string}>={
 Nexp:{title:t('Expunerea pune în mișcare actualizarea','Exposure triggers the update'),body:t('Fiecare eveniment de expunere mărește familiaritatea. Numărul expunerilor rămâne constant între evenimente, chiar dacă timpul continuă să treacă.','Each exposure event increases familiarity. The exposure count stays constant between events, even as time continues.'),formula:'F′ = F + αf(1 − F)',limit:t('Numărul expunerilor nu măsoară adevărul afirmației.','The exposure count does not measure the truth of the claim.')},
 F:{title:t('Familiaritatea contribuie la convingere','Familiarity contributes to belief'),body:t('Fiecare nouă expunere adaugă mai puțină familiaritate, pe măsură ce F se apropie de 1. În M0, F nu scade automat cu timpul. Termenul său se adună cu convingerea inițială, evidența și corecția înainte de transformarea logistică.','Each new exposure adds less familiarity as F approaches 1. In M0, F does not automatically decay with time. Its term is added to prior belief, evidence and correction before the logistic transform.'),value:frame.familiarity,before:previous?.familiarity,formula:'zB += βf × F',term:e.belief_terms.familiarity,limit:t('Familiaritatea poate crește fără informație factuală nouă. Contribuția la scor nu este un efect procentual asupra B.','Familiarity can rise without new factual information. Its score contribution is not a percentage effect on B.')},
 C:{title:t('Corecția are accesibilitate și direcție','Correction has accessibility and direction'),body:t(`Accesibilitatea C multiplică direcția ${sign(e.inputs.correction_direction)}. Cu direcție negativă, contribuția la scor este negativă. Când C scade, contribuția se apropie de zero; familiaritatea nu este ștearsă.`,`Accessibility C multiplies direction ${sign(e.inputs.correction_direction)}. With a negative direction, its score contribution is negative. As C decays, that contribution approaches zero; familiarity is not erased.`),value:frame.correction,before:previous?.correction,formula:'zB += βcorrection × C × direction',term:e.belief_terms.correction,limit:t('O corecție nu reduce universal B: sensul depinde de direcția sa în model.','A correction does not universally reduce B: direction determines its sign in the model.')},
 T:{title:t('Sursa ponderează semnalul de evidență','The source weights the evidence signal'),body:t(`Semnalul acestui pas este ${sign(e.inputs.evidence_signal)}. Formula îl multiplică cu 2T − 1 = ${sign(2*frame.reliability-1)}. La T = 0,5 termenul este nul; sub acest prag, semnul semnalului este inversat.`,`This step’s signal is ${sign(e.inputs.evidence_signal)}. The formula multiplies it by 2T − 1 = ${sign(2*frame.reliability-1)}. At T = 0.5 the term is zero; below this threshold, the signal’s sign is reversed.`),value:frame.reliability,before:previous?.reliability,formula:'zB += βsource × evidence × (2T − 1)',term:e.belief_terms.evidence,limit:t('Această inversare este o alegere necalibrată a M0. Scenariul sursei schimbă atât feedbackul, cât și semnalul față de repetiție.','This reversal is an uncalibrated M0 choice. The source scenario changes both feedback and signal relative to repetition.')},
 B:{title:t('Convingerea rezultă din integrarea termenilor','Belief results from combining the terms'),body:t(`Scorul ${sign(e.belief_logit)} combină convingerea inițială, familiaritatea, evidența ponderată și corecția. Transformarea logistică produce B = ${n(frame.belief)}. B de la pasul anterior nu înlocuiește convingerea inițială.`,`Score ${sign(e.belief_logit)} combines prior belief, familiarity, weighted evidence and correction. The logistic transform gives B = ${n(frame.belief)}. The previous step’s B does not replace the prior.`),value:frame.belief,before:previous?.belief,formula:'B = logistic(logit(prior) + βf F + βsource evidence (2T − 1) + βcorrection C direction)',limit:t('B este judecata simulată, nu adevărul afirmației și nici acțiunea de distribuire.','B is the simulated judgment, not the claim’s truth or the sharing action.')},
 W:{title:t('Acuratețea schimbă ponderile deciziei','Accuracy changes the decision weights'),body:t(`Indiciu de acuratețe: ${e.inputs.accuracy_cue?'da':'nu'}. W ponderează termenul convingerii, iar 1 − W ponderează recompensa. Indiciul nu modifică direct B; o pondere mai mare poate crește sau reduce P în funcție de convingere și recompensă.`,`Accuracy cue: ${e.inputs.accuracy_cue?'yes':'no'}. W weights belief, while 1 − W weights reward. The cue does not directly change B; greater weight can raise or lower P depending on belief and reward.`),value:frame.accuracy_weight,before:previous?.accuracy_weight,formula:'u = bias + W(2B − 1) + βreward(1 − W)reward',limit:t('W nu măsoară raționalitatea generală. Mărimea unui termen nu stabilește prioritatea intervenției.','W does not measure general rationality. A term’s size does not establish intervention priority.')},
 P:{title:t('Scorul deciziei devine probabilitate','The decision score becomes probability'),body:t(`Convingere ponderată: ${sign(e.sharing_terms.belief)}; recompensă ponderată: ${sign(e.sharing_terms.reward)}; bias: ${sign(e.sharing_terms.bias)}. Suma ${sign(e.sharing_logit)} este transformată în P = ${n(frame.share_probability)}.`,`Weighted belief: ${sign(e.sharing_terms.belief)}; weighted reward: ${sign(e.sharing_terms.reward)}; bias: ${sign(e.sharing_terms.bias)}. Their sum ${sign(e.sharing_logit)} is transformed into P = ${n(frame.share_probability)}.`),value:frame.share_probability,before:previous?.share_probability,formula:'P = logistic(u)',limit:t('P descrie probabilitatea unei acțiuni simulate, nu proporția estimată a unei populații reale.','P describes the probability of a simulated action, not an estimated real-population proportion.')},
 Share:{title:t('Acțiunea este extrasă aleator','The action is sampled'),body:t(`La P = ${n(frame.share_probability)}, jurnalul înregistrează distribuire: ${frame.share?'da':'nu'}. O extragere uniformă este comparată cu P; acțiunea poate varia între pași cu aceeași probabilitate.`,`At P = ${n(frame.share_probability)}, the log records sharing: ${frame.share?'yes':'no'}. A uniform draw is compared with P; actions can differ between steps with identical probability.`),value:Number(frame.share),before:previous?Number(previous.share):undefined,formula:'Share = [r < P], r ∼ Uniform(0,1)',limit:t('Nu se folosește un prag P > 0,5. M0 nu trimite automat distribuirea înapoi către expuneri.','No P > 0.5 threshold is used. M0 does not automatically feed sharing back into exposures.')}
 };
 const r=readings[node];if(!r)return '';
 return `<h3>${r.title}</h3><p>${r.body}</p>${r.value===undefined?'':`<p class="reading-values">${node} = <strong>${n(r.value)}</strong> · ${r.before===undefined?t('Pas inițial','Initial step'):`Δ = ${sign(r.value-r.before)} ${t('față de pasul anterior','from the previous step')}`}</p>`}${r.formula?`<details><summary>${t('Formula și contribuția','Formula and contribution')}</summary><p class="equation">${r.formula.replaceAll('<','&lt;')}</p>${r.term===undefined?'':`<p>${t('Termen în scorul convingerii','Term in the belief score')}: <strong>${sign(r.term)}</strong></p>`}</details>`:''}<p class="note">${r.limit}</p>`;
}
