export type Schedule={mask:number;start:number;frames:{time:number;exposure:boolean;exposure_prevented:boolean;correction:boolean;source_feedback:boolean;accuracy_cue:boolean}[]};
export function renderSchedule(schedule:Schedule,lang:'ro'|'en'){
 const t=(ro:string,en:string)=>lang==='ro'?ro:en;
 const times=(key:'exposure_prevented'|'correction'|'source_feedback'|'accuracy_cue')=>schedule.frames.filter(f=>f[key]).map(f=>f.time).join(', ');
 const actions=[
  {bit:1,name:t('Reducerea repetiției','Reduce repetition'),when:times('exposure_prevented'),detail:t('Sunt prevenite numai expunerile încă programate. Familiaritatea deja acumulată rămâne.','Only remaining scheduled exposures are prevented. Already accumulated familiarity remains.')},
  {bit:2,name:t('Context corectiv verificat','Verified corrective context'),when:times('correction'),detail:t('O singură introducere: direcție −1 pentru afirmația falsă și +1 pentru cea adevărată. Accesibilitatea scade ulterior.','One introduction: direction −1 for the false claim and +1 for the true claim. Accessibility subsequently decays.')},
  {bit:4,name:t('Indiciu de acuratețe','Accuracy cue'),when:times('accuracy_cue'),detail:t('Indiciul este prezent la fiecare decizie indicată, fără să schimbe direct convingerea.','The cue is present at each indicated decision, without directly changing belief.')},
  {bit:8,name:t('Feedback despre sursă','Source feedback'),when:times('source_feedback'),detail:t('Confirmări corecte despre sursa informativă, pentru ambele afirmații sintetice.','Correct confirmations about the informative source, for both synthetic claims.')}
 ].filter(a=>schedule.mask&a.bit);
 return `<section id="schedulePanel"><h4>${t('Calendarul combinației inspectate','Inspected bundle schedule')}</h4><p>${t('Pașii sunt unități abstracte, nu zile sau ani. Calendarul descrie rularea simulată; nu stabilește un program de implementare în populație.','Steps are abstract units, not days or years. This schedule describes the simulated run; it does not set a population implementation timetable.')}</p><div class="table-scroll"><table id="actionSchedule"><caption>${t('Măsuri selectate și momente efective','Selected measures and effective timing')}</caption><thead><tr><th scope="col">${t('Măsură','Measure')}</th><th scope="col">${t('Pași efectivi','Effective steps')}</th><th scope="col">${t('Ce se întâmplă','What happens')}</th></tr></thead><tbody>${actions.map(a=>`<tr data-action="${a.bit}"><th scope="row">${a.name}</th><td>${a.when||t('Niciunul','None')}</td><td>${a.when?a.detail:t('Activarea la pasul 5 este prea târzie: toate cele patru expuneri au avut deja loc.','Activation at step 5 is too late: all four exposures have already occurred.')}</td></tr>`).join('')||`<tr><td colspan="3">${t('Fără măsuri: rulează numai expunerile de bază și deciziile.','No measures: only baseline exposures and decisions run.')}</td></tr>`}</tbody></table></div><details><summary>${t('Vezi ordinea evenimentelor la fiecare pas','View the event order at every step')}</summary><p class="note">${t('În cadrul unui pas: expunere (dacă există), corecție, feedback despre sursă, apoi decizie. Expunerea prevenită nu este un eveniment executat.','Within a step: exposure (if present), correction, source feedback, then decision. A prevented exposure is not an executed event.')}</p><div class="table-scroll"><table id="eventSchedule"><caption>${t('Jurnalul programării, pașii 0–12','Scheduling ledger, steps 0–12')}</caption><thead><tr><th scope="col">${t('Pas','Step')}</th><th scope="col">${t('Expunere','Exposure')}</th><th scope="col">${t('Corecție','Correction')}</th><th scope="col">${t('Feedback','Feedback')}</th><th scope="col">${t('Decizie','Decision')}</th></tr></thead><tbody>${schedule.frames.map(f=>`<tr data-time="${f.time}"><th scope="row">${f.time}</th><td>${f.exposure?t('Executată','Executed'):f.exposure_prevented?t('Prevenită','Prevented'):'—'}</td><td>${f.correction?t('Introducere','Introduction'):'—'}</td><td>${f.source_feedback?t('Confirmare','Confirmation'):'—'}</td><td>${f.accuracy_cue?t('Cu indiciu de acuratețe','With accuracy cue'):t('Fără indiciu','Without cue')}</td></tr>`).join('')}</tbody></table></div></details></section>`;
}
