type Lang='ro'|'en';
type Bundle={mask:number;start:number;false_share:number;true_share:number;false_belief:number;true_belief:number;false_share_path:number[];true_share_path:number[]};
type Lever={id:string;bit:number;label:Record<Lang,string>;factor:string;action:Record<Lang,string>};
export type PlanningData={model_version:string;horizon:number[];evaluation:string;levers:Lever[];profiles:{id:string;scale:number;parameters:Record<string,number>;bundles:Bundle[]}[]};
const settings={budget:3,weight:50,start:2,profile:'reference',enabled:15,costs:[1,1,1,1]};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function mountPlanner(host:HTMLElement,data:PlanningData,lang:Lang){
 const tr=(ro:string,en:string)=>lang==='ro'?ro:en;
 const n=(v:number)=>v.toLocaleString(lang==='ro'?'ro-RO':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
 const profileName=(id:string)=>({low:tr('Răspuns redus','Lower response'),reference:tr('Referință','Reference'),high:tr('Răspuns crescut','Higher response')}[id]!);
 const names=(mask:number)=>data.levers.filter(l=>mask&l.bit).map(l=>l.label[lang]).join(' + ')||tr('Fără măsuri','No measures');
 const cost=(mask:number)=>data.levers.reduce((a,l,i)=>a+((mask&l.bit)?settings.costs[i]:0),0);
 const score=(b:Bundle)=>100*(settings.weight/100*(1-b.false_share)+(1-settings.weight/100)*b.true_share);
 const rows=(profile:string)=>data.profiles.find(p=>p.id===profile)!.bundles.filter(b=>b.start===settings.start);
 const candidates=(profile:string)=>rows(profile).filter(b=>(b.mask&settings.enabled)===b.mask&&cost(b.mask)<=settings.budget).sort((a,b)=>score(b)-score(a)||cost(a.mask)-cost(b.mask)||a.mask-b.mask);
 const base=(profile:string)=>rows(profile).find(b=>b.mask===0)!;
 let inspected:number|undefined;
 host.innerHTML=`<div class="section-heading"><div><h2>${tr('Laborator de intervenții','Intervention lab')}</h2><p>${tr('Compară 16 combinații în M0. Prioritățile sunt condiționate de obiectiv, efort și ipoteze; nu sunt recomandări validate pentru populație.','Compare 16 M0 bundles. Priorities depend on objectives, effort and assumptions; they are not validated population recommendations.')}</p></div><span class="planner-badge">${tr('SIMULARE EXPLORATORIE','EXPLORATORY SIMULATION')}</span></div>
 <div class="planner-layout"><aside class="panel planner-controls"><h3>${tr('1. Definește decizia','1. Define the decision')}</h3><label for="budget">${tr('Buget de efort (unități estimate)','Effort budget (estimated units)')}</label><input id="budget" type="number" required min="0" max="80" step="1" value="${settings.budget}"><label for="objective">${tr('Importanța reducerii distribuirii false','Weight on reducing false sharing')}: <output id="objectiveValue">${settings.weight}%</output></label><input id="objective" type="range" min="0" max="100" step="10" value="${settings.weight}"><p class="note">${tr('Restul ponderii revine păstrării distribuirii adevărate. Rezultatele se evaluează pe toți cei 13 pași.','The remaining weight goes to preserving true sharing. Outcomes are evaluated over all 13 steps.')}</p><label for="timing">${tr('Activarea măsurilor','Intervention activation')}</label><select id="timing"><option value="2" ${settings.start===2?'selected':''}>${tr('Devreme · pasul 2','Early · step 2')}</option><option value="5" ${settings.start===5?'selected':''}>${tr('Mai târziu · pasul 5','Later · step 5')}</option></select><label for="assumption">${tr('Ipoteza de răspuns','Response assumption')}</label><select id="assumption">${data.profiles.map(p=>`<option value="${p.id}" ${p.id===settings.profile?'selected':''}>${profileName(p.id)}</option>`).join('')}</select><p class="note">${tr('Trei coeficienți variază împreună cu ±30%. Acesta este un test limitat de sensibilitate, nu un interval de încredere.','Three coefficients vary together by ±30%. This is a limited sensitivity check, not a confidence interval.')}</p><details><summary>${tr('Ipoteze și calcul','Assumptions and calculation')}</summary><p>${tr('Două afirmații sintetice, una falsă și una adevărată; convingere inițială 0,5; sursă informativă; semnal de evidență ±0,6; fact-check corect. Aceste condiții favorabile nu sunt garantate în practică.','Two synthetic claims, one false and one true; prior belief 0.5; informative source; evidence signal ±0.6; correct fact-checking. These favorable conditions are not guaranteed in practice.')}</p><p>${tr('Scor = 100 × [pondere × (1 − P distribuirii false) + (1 − pondere) × P distribuirii adevărate]. Se folosesc mediile celor 13 pași.','Score = 100 × [weight × (1 − false-sharing probability) + (1 − weight) × true-sharing probability]. Probabilities are averaged over 13 steps.')}</p><p>${tr('Variază beta_f, beta_correction și beta_accuracy_cue. Eforturile sunt presupuse aditive și nu sunt costuri observate.','beta_f, beta_correction and beta_accuracy_cue vary. Efforts are assumed additive and are not observed costs.')}</p></details></aside>
 <div class="planner-main"><section class="panel"><h3>${tr('2. Măsuri și factorii abordați','2. Measures and targeted factors')}</h3><div class="lever-grid">${data.levers.map((l,i)=>`<article><label class="lever-title"><input type="checkbox" data-lever="${i}" ${(settings.enabled&l.bit)?'checked':''}>${esc(l.label[lang])}</label><p class="factor-path">${esc(l.factor)}</p><p>${esc(l.action[lang])}</p><label class="effort-label" for="cost-${i}">${tr('Efort estimat','Estimated effort')}<input type="number" required id="cost-${i}" data-cost="${i}" min="1" max="20" step="1" value="${settings.costs[i]}"></label></article>`).join('')}</div></section><section class="panel" id="recommendation" aria-live="polite"></section><section class="panel" id="comparison"></section><section class="panel" id="planDetails"></section></div></div>`;
 function draw(){
  const ranked=candidates(settings.profile),best=ranked[0],baseline=base(settings.profile);
  const gain=(b:Bundle)=>score(b)-score(baseline);
  const stability=data.profiles.filter(p=>candidates(p.id)[0].mask===best.mask).length;
  const ranges=data.profiles.map(p=>score(rows(p.id).find(b=>b.mask===best.mask)!)-score(base(p.id)));
  host.querySelector('#recommendation')!.innerHTML=`<p class="eyebrow">${tr('3. CEA MAI BUNĂ COMBINAȚIE FEZABILĂ ÎN ACEST TEST','3. BEST FEASIBLE BUNDLE IN THIS TEST')}</p><h2 id="bestBundle" data-mask="${best.mask}">${esc(names(best.mask))}</h2><div class="planner-metrics"><div><span>${tr('Câștig față de absența măsurilor','Gain vs no measures')}</span><strong id="bestGain">${n(gain(best))}</strong><small>${tr('puncte de scor · medie pe 13 pași','score points · 13-step average')}</small></div><div><span>${tr('Efort / buget','Effort / budget')}</span><strong>${cost(best.mask)} / ${settings.budget}</strong><small>${tr('unități introduse de utilizator','user-supplied units')}</small></div><div><span>${tr('Rămâne prima alegere','Remains top-ranked')}</span><strong>${stability} / 3</strong><small>${tr('ipoteze exploratorii, nu probabilitate','exploratory assumptions, not probability')}</small></div></div><p class="note">${tr('Intervalul câștigului pentru această combinație în cele trei ipoteze','Gain range for this bundle across the three assumptions')}: ${n(Math.min(...ranges))} – ${n(Math.max(...ranges))}. ${tr('Optimizarea compară toate combinațiile disponibile sub buget; egalitățile favorizează efortul mai mic.','Optimization compares every available bundle within budget; ties favor lower effort.')}</p>`;
  host.querySelector('#comparison')!.innerHTML=`<h3>${tr('Compară opțiunile fezabile','Compare feasible options')}</h3><p class="note">${tr('Scorul nu este o probabilitate. P(false) și P(true) sunt probabilități de distribuire, nu prevalențe.','The score is not a probability. P(false) and P(true) are sharing probabilities, not prevalences.')}</p><div class="table-scroll"><table class="planning-table"><thead><tr><th>${tr('Combinație','Bundle')}</th><th>${tr('Efort','Effort')}</th><th>${tr('Câștig','Gain')}</th><th>P(false)</th><th>P(true)</th><th>${tr('Inspectează','Inspect')}</th></tr></thead><tbody>${ranked.map(b=>`<tr data-plan-mask="${b.mask}"><td>${esc(names(b.mask))}</td><td>${cost(b.mask)}</td><td>${n(gain(b))}</td><td>${n(b.false_share)}</td><td>${n(b.true_share)}</td><td><button data-inspect="${b.mask}">${tr('Detalii','Details')}</button></td></tr>`).join('')}</tbody></table></div>`;
  if(inspected===undefined||!ranked.some(b=>b.mask===inspected))inspected=best.mask;
  details(rows(settings.profile).find(b=>b.mask===inspected)!);
  host.querySelectorAll<HTMLButtonElement>('[data-inspect]').forEach(b=>b.onclick=()=>{inspected=Number(b.dataset.inspect);details(rows(settings.profile).find(r=>r.mask===inspected)!);});
 }
 function details(bundle:Bundle){
  const baseline=base(settings.profile),all=rows(settings.profile);
  const gain=score(bundle)-score(baseline);
  const isolated=data.levers.filter(l=>l.bit&bundle.mask).reduce((sum,l)=>sum+score(all.find(b=>b.mask===l.bit)!)-score(baseline),0);
  const contributions=data.levers.filter(l=>l.bit&bundle.mask).map(l=>({l,loss:score(bundle)-score(all.find(b=>b.mask===(bundle.mask&~l.bit))!)})).sort((a,b)=>b.loss-a.loss);
  host.querySelector('#planDetails')!.innerHTML=`<h3>${tr('4. Interacțiuni și plan de verificare','4. Interactions and verification plan')}</h3><p><strong>${esc(names(bundle.mask))}</strong></p><div class="bundle-effects"><p>${tr('Câștigul combinat','Combined gain')}: <b>${n(gain)}</b></p><p>${tr('Suma câștigurilor izolate','Sum of standalone gains')}: <b>${n(isolated)}</b></p><p>${tr('Diferență de interacțiune','Interaction difference')}: <b id="interactionGain">${n(gain-isolated)}</b></p></div><p class="note">${tr('Diferența pozitivă indică un efect peste suma măsurilor izolate, iar cea negativă indică suprapunere sau antagonism în această simulare. Nu dovedește sinergie reală.','A positive difference exceeds the sum of standalone measures; a negative difference indicates overlap or antagonism in this simulation. It does not establish real-world synergy.')}</p><h4>${tr('Prioritatea factorilor în combinația inspectată','Factor priority within the inspected bundle')}</h4><ol class="factor-priorities">${contributions.map(({l,loss})=>`<li><strong>${esc(l.label[lang])}</strong> · ${tr('pierdere la eliminare','loss if removed')}: ${n(loss)}<div class="priority-bar"><span style="width:${Math.max(0,Math.min(100,Math.abs(loss)*8))}%"></span></div><small>${esc(l.factor)}</small></li>`).join('')||`<li>${tr('Nicio măsură selectată.','No measure selected.')}</li>`}</ol><p class="note">${tr('Contribuții condiționate de celelalte măsuri; nu sunt ponderi universale ale factorilor și nu se însumează obligatoriu la câștigul total.','Contributions conditional on the other measures; not universal factor weights and not necessarily additive.')}</p><h4>${tr('Calendarul simulat','Simulated schedule')}</h4><p>${tr('Activare la pasul','Activation at step')} ${settings.start}. ${tr('Contextul corectiv este introdus o dată; feedbackul despre sursă se repetă la fiecare doi pași, de patru ori. Evaluarea acoperă pașii 0–12. Reducerea repetiției începută după pasul 4 nu mai poate elimina expunerile anterioare.','Corrective context is introduced once; source feedback repeats every two steps, four times. Evaluation covers steps 0–12. Repetition reduction starting after step 4 cannot undo past exposures.')}</p><h4>${tr('Înaintea aplicării în practică','Before real-world implementation')}</h4><p>${tr('Definește populația și indicatorii, verifică fezabilitatea măsurilor selectate, măsoară costurile și efectele adverse, apoi testează pachetul față de un comparator. Stresul, somnul, instituțiile și amplificarea algoritmică nu sunt încă factori executabili în M0.','Define the population and outcomes, verify feasibility of the selected measures, measure costs and adverse effects, then test the bundle against a comparator. Stress, sleep, institutions and algorithmic amplification are not yet executable M0 factors.')}</p><button id="exportPlan">${tr('Descarcă analiza și ipotezele JSON ↓','Download analysis and assumptions JSON ↓')}</button>`;
  host.querySelector<HTMLButtonElement>('#exportPlan')!.onclick=()=>{const payload={model_version:data.model_version,purpose:data.evaluation,settings:{...settings},bundle,score:score(bundle),gain,interaction:gain-isolated,profile:data.profiles.find(p=>p.id===settings.profile),scope:'Illustrative, uncalibrated; not a population recommendation'};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cem-intervention-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }
 host.querySelector<HTMLInputElement>('#budget')!.onchange=e=>{const x=e.target as HTMLInputElement;if(!x.reportValidity())return;settings.budget=Number(x.value);inspected=undefined;draw();};
 host.querySelector<HTMLInputElement>('#objective')!.oninput=e=>{settings.weight=Number((e.target as HTMLInputElement).value);host.querySelector('#objectiveValue')!.textContent=settings.weight+'%';inspected=undefined;draw();};
 host.querySelector<HTMLSelectElement>('#timing')!.onchange=e=>{settings.start=Number((e.target as HTMLSelectElement).value);inspected=undefined;draw();};
 host.querySelector<HTMLSelectElement>('#assumption')!.onchange=e=>{settings.profile=(e.target as HTMLSelectElement).value;inspected=undefined;draw();};
 host.querySelectorAll<HTMLInputElement>('[data-lever]').forEach(x=>x.onchange=()=>{const bit=data.levers[Number(x.dataset.lever)].bit;settings.enabled=x.checked?settings.enabled|bit:settings.enabled&~bit;inspected=undefined;draw();});
 host.querySelectorAll<HTMLInputElement>('[data-cost]').forEach(x=>x.onchange=()=>{if(!x.reportValidity())return;settings.costs[Number(x.dataset.cost)]=Number(x.value);inspected=undefined;draw();});
 draw();
}
